from .dashboard import MediaDashboardView
from .month_plan import (
    MediaMonthPlanCreateView,
    MediaMonthPlanDetailView,
    MediaMonthPlanWizardView,
    MediaPlanToggleEventView,
    MediaPlanToggleCategoryView,
    MediaContentCategoryCreateView,
    MediaPlanCreateEventView,
    MediaPlanMacroEventView,
    MediaPlanMacroCategoryView,
)
from .event_contents import MediaEventContentsView
from .category_contents import MediaCategoryContentsView
from .demands_create import MediaDemandQuickCreateView, MediaDemandQuickUpdateView, MediaEventQuickCreateView, MediaEventTypeQuickCreateView
from .content import (
    MediaContentListView,
    MediaDemandsPanelView,
    MediaContentCreateView,
    MediaContentUpdateView,
    MediaContentDeleteView,
    MediaTaskCreateView,
    MediaTaskUpdateStatusView,
    MediaTaskUpdateDescriptionView,
    MediaCommentCreateView,
    MediaAttachmentCreateView,
)
from .calendar import MediaCalendarView, MediaCalendarEventsAPIView, MediaCalendarUpdateView
from .event_types import MediaEventTypeListView, MediaEventTypeCreateView, MediaEventTypeUpdateView, MediaEventTypeDeleteView
from .templates_mgmt import (
    MediaTemplateListView,
    MediaTemplateCreateView,
    MediaTemplateSetupView,
    MediaTemplateDetailView,
    MediaTemplateUpdateView,
    MediaTemplateItemCreateView,
    MediaTemplateItemUpdateView,
    MediaTemplateItemDeleteView,
)
from .template_apply import MediaEventSetTypeView, MediaApplyTemplateView
from .organization import (
    MediaOrganizationDashboardView,
    MediaSubTeamListView,
    MediaSubTeamCreateView,
    MediaSubTeamDetailView,
    MediaSubTeamUpdateView,
    MediaSubTeamMemberAddView,
    MediaSubTeamMemberUpdateView,
    MediaSubTeamMemberRemoveView,
    MediaRoleListView,
    MediaRoleCreateView,
    MediaLeadershipListView,
    MediaLeadershipCreateView,
    MediaLeadershipUpdateView,
    MediaResourceListView,
    MediaResourceCreateView,
    MediaResourceDetailView,
    MediaResourceUpdateView,
    MediaResourceCredentialUpdateView,
    MediaResourceCredentialRevealView,
)

__all__ = [
    'MediaDashboardView',
    'MediaMonthPlanCreateView',
    'MediaMonthPlanDetailView',
    'MediaMonthPlanWizardView',
    'MediaPlanToggleEventView',
    'MediaPlanToggleCategoryView',
    'MediaContentCategoryCreateView',
    'MediaPlanCreateEventView',
    'MediaPlanMacroEventView',
    'MediaPlanMacroCategoryView',
    'MediaEventContentsView',
    'MediaCategoryContentsView',
    'MediaContentListView',
    'MediaDemandsPanelView',
    'MediaDemandQuickCreateView',
    'MediaDemandQuickUpdateView',
    'MediaEventQuickCreateView',
    'MediaEventTypeQuickCreateView',
    'MediaContentCreateView',
    'MediaContentUpdateView',
    'MediaContentDeleteView',
    'MediaTaskCreateView',
    'MediaTaskUpdateStatusView',
    'MediaTaskUpdateDescriptionView',
    'MediaCommentCreateView',
    'MediaAttachmentCreateView',
    'MediaCalendarView',
    'MediaCalendarEventsAPIView',
    'MediaCalendarUpdateView',
    'MediaEventTypeListView',
    'MediaEventTypeCreateView',
    'MediaEventTypeUpdateView',
    'MediaEventTypeDeleteView',
    'MediaTemplateListView',
    'MediaTemplateCreateView',
    'MediaTemplateSetupView',
    'MediaTemplateDetailView',
    'MediaTemplateUpdateView',
    'MediaTemplateItemCreateView',
    'MediaTemplateItemUpdateView',
    'MediaTemplateItemDeleteView',
    'MediaEventSetTypeView',
    'MediaApplyTemplateView',
    'MediaOrganizationDashboardView',
    'MediaSubTeamListView',
    'MediaSubTeamCreateView',
    'MediaSubTeamDetailView',
    'MediaSubTeamUpdateView',
    'MediaSubTeamMemberAddView',
    'MediaSubTeamMemberUpdateView',
    'MediaSubTeamMemberRemoveView',
    'MediaRoleListView',
    'MediaRoleCreateView',
    'MediaLeadershipListView',
    'MediaLeadershipCreateView',
    'MediaLeadershipUpdateView',
    'MediaResourceListView',
    'MediaResourceCreateView',
    'MediaResourceDetailView',
    'MediaResourceUpdateView',
    'MediaResourceCredentialUpdateView',
    'MediaResourceCredentialRevealView',
]
