version: '3'

services:
  connect-database: 
    image: postgres:latest 
    container_name: connect-database  
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - connect-network

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - connect-network

  web-project:
    hostname: "${HOSTNAME}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/platform
    command: [
      "sh",
      "-c",
      "pip install debugpy && python -m debugpy --listen 0.0.0.0:3000 --wait-for-client -m gunicorn -b 0.0.0.0:${PORT} connect.wsgi:application"
    ]
    volumes:
      - ./:/usr/src/platform
      - media_volume:/usr/src/platform/media
    ports:
      - "${PORT}:${PORT}"
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
      - REDIS_URL=redis://redis:6379
    env_file:
      .env
    depends_on:
      - connect-database 
      - redis
    networks:
      - connect-network

networks:
  connect-network:
    external: true

volumes:
  postgres_data:
  redis_data:
  media_volume:
    connect-network:
        external: true