# Generated by Django 4.2.16 on 2025-08-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='spiritual_maturity',
        ),
    ]
