# Generated by Django 4.2.16 on 2025-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_user_avatar_user_bio_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ministry',
        ),
        migrations.AddField(
            model_name='member',
            name='ministry',
            field=models.ManyToManyField(blank=True, to='website.ministry'),
        ),
    ]
