# Generated by Django 4.2.16 on 2025-08-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_member_ministry_member_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='wants_home_prayer',
            field=models.BooleanField(default=False, verbose_name='Deseja oração na casa?'),
        ),
    ]
