# Generated by Django 4.2.16 on 2025-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_visitor_wants_home_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Marque esta opção se o evento ocorre regularmente (semanal, mensal, etc.)', verbose_name='Evento Recorrente'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_description',
            field=models.CharField(blank=True, help_text="Descreva detalhes adicionais sobre a recorrência (ex: 'Todo domingo às 10h')", max_length=255, null=True, verbose_name='Descrição da Recorrência'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal'), ('custom', 'Personalizado')], help_text='Selecione a frequência com que o evento se repete', max_length=20, null=True, verbose_name='Padrão de Recorrência'),
        ),
    ]
