# Generated by Django 4.2.16 on 2025-09-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_event_is_recurring_event_recurrence_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_type',
            field=models.CharField(blank=True, choices=[('registration', 'Inscrição'), ('more_info', 'Saiba Mais'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('contact', 'Contato'), ('other', 'Outro')], default='more_info', help_text='Selecione o tipo de link para personalizar o botão', max_length=20, null=True, verbose_name='Tipo de Link'),
        ),
    ]
