# Generated by Django 4.2.16 on 2025-09-17 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_event_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenDebtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de WhatsApp')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição dos Itens')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Fiado da Cantina',
                'verbose_name_plural': 'Fiados da Cantina',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
