# Generated by Django 4.2.16 on 2025-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_canteendebtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'Membro (Sem acesso ao painel)'), ('admin', 'Administrador (Acesso total)'), ('canteen', 'Cantina (Gerencia fiados)'), ('visitors', 'Visitantes (Gerencia visitantes)'), ('consolidation', 'Consolidação (Gerencia acompanhamentos)'), ('events', 'Eventos (Gerencia eventos)')], default='member', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
