# Generated by Django 4.2.16 on 2025-11-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_followuptemplate_followup_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followupreport',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='followup',
            name='current_week',
            field=models.PositiveIntegerField(default=1, help_text='Semana atual'),
        ),
        migrations.AddField(
            model_name='followup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='attended_service',
            field=models.BooleanField(default=False, verbose_name='Participou do culto?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='building_relationships',
            field=models.BooleanField(default=False, verbose_name='Está criando vínculos com outros membros?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='has_spiritual_life',
            field=models.BooleanField(default=False, help_text='Frutos do Espírito visíveis: amor, alegria, paz, paciência, bondade, etc.', verbose_name='Demonstra vida do Espírito Santo?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='lifestyle_changes',
            field=models.BooleanField(default=False, verbose_name='Demonstra mudanças no estilo de vida?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='overcoming_struggles',
            field=models.BooleanField(default=False, verbose_name='Vencendo lutas/vícios anteriores?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='praying_regularly',
            field=models.BooleanField(default=False, verbose_name='Está orando regularmente?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='reading_bible',
            field=models.BooleanField(default=False, verbose_name='Está lendo a Bíblia?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='week',
            field=models.PositiveIntegerField(default=1, help_text='Semana referente a este relatório'),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='description',
            field=models.TextField(help_text='Como foi o andamento nesta semana?'),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='status',
            field=models.CharField(choices=[('excellent', 'Excelente progresso'), ('good', 'Bom progresso'), ('regular', 'Progresso regular'), ('needs_support', 'Precisa de apoio'), ('difficult', 'Enfrentando dificuldades'), ('no_contact', 'Sem contato')], max_length=30),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='type',
            field=models.CharField(choices=[('consolidation', 'Consolidação'), ('discipleship', 'Discipulado')], default='consolidation', max_length=20),
        ),
        migrations.AlterField(
            model_name='followuptemplatestep',
            name='description',
            field=models.TextField(blank=True, help_text='Dicas e orientações para esta semana', null=True),
        ),
        migrations.AlterField(
            model_name='followuptemplatestep',
            name='title',
            field=models.CharField(help_text='Título/tema da semana', max_length=200),
        ),
        migrations.AlterField(
            model_name='followuptemplatestep',
            name='week',
            field=models.PositiveIntegerField(help_text='Número da semana'),
        ),
        migrations.DeleteModel(
            name='FollowUpStep',
        ),
    ]
