# Generated by Django 4.2.16 on 2025-11-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_followupreport_options_followup_current_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupreport',
            name='has_spiritual_life',
        ),
        migrations.AddField(
            model_name='followupreport',
            name='attending_classes',
            field=models.BooleanField(default=False, verbose_name='Participou das aulas de consolidação?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='is_receptive',
            field=models.BooleanField(default=False, help_text='Demonstra abertura e interesse nas conversas', verbose_name='Está receptivo esta semana?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='met_in_group',
            field=models.BooleanField(default=False, verbose_name='Saiu em grupo esta semana?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='met_one_on_one',
            field=models.BooleanField(default=False, verbose_name='Saiu sozinho com o consolidador esta semana?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='responding_messages',
            field=models.BooleanField(default=False, verbose_name='Respondeu mensagens esta semana?'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='volunteering',
            field=models.BooleanField(default=False, verbose_name='Participou como voluntário esta semana?'),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='status',
            field=models.CharField(choices=[('excellent', '🌟 Excelente'), ('good', '😊 Bom'), ('regular', '😐 Regular'), ('difficult', '😟 Difícil'), ('no_contact', '📵 Não consegui contato')], max_length=30),
        ),
    ]
