# Generated by Django 4.2.16 on 2025-11-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_followupreport_has_spiritual_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_approver',
            field=models.BooleanField(default=False, help_text='Membro pode aprovar palavras de conhecimento de outros ministradores', verbose_name='Aprovador de Palavras'),
        ),
        migrations.CreateModel(
            name='WordOfKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('word', models.TextField(verbose_name='Palavra de Conhecimento')),
                ('service_type', models.CharField(choices=[('wednesday', 'Quarta-feira'), ('sunday', 'Domingo')], editable=False, max_length=20, verbose_name='Tipo de Culto')),
                ('service_date', models.DateField(editable=False, verbose_name='Data do Culto')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('resulted_in_healing', models.BooleanField(default=False, verbose_name='Resultou em Cura')),
                ('is_approved', models.BooleanField(default=False, help_text='Palavra aprovada para o culto', verbose_name='Aprovada')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_words', to='website.member', verbose_name='Aprovada por')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_of_knowledge', to='website.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Palavra de Conhecimento',
                'verbose_name_plural': 'Palavras de Conhecimento',
                'ordering': ['-service_date', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MinistrationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('week_start_date', models.DateField(help_text='Data de início da semana (geralmente segunda-feira)', unique=True, verbose_name='Início da Semana')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('leaders', models.ManyToManyField(blank=True, limit_choices_to={'ministry__name__icontains': 'ministração'}, related_name='ministration_schedules_as_leader', to='website.member', verbose_name='Líderes da Escala')),
                ('members', models.ManyToManyField(limit_choices_to={'ministry__name__icontains': 'ministração'}, related_name='ministration_schedules', to='website.member', verbose_name='Ministradores Escalados')),
            ],
            options={
                'verbose_name': 'Escala de Ministração',
                'verbose_name_plural': 'Escalas de Ministração',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Healing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='Descrição da Cura')),
                ('healed_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Pessoa Curada')),
                ('body_part', models.CharField(blank=True, help_text='Ex: perna, olho, cabeça', max_length=255, null=True, verbose_name='Parte do Corpo')),
                ('condition', models.CharField(blank=True, help_text='Ex: perna quebrada, cegueira, enxaqueca', max_length=255, null=True, verbose_name='Condição')),
                ('healing_type', models.CharField(choices=[('total', 'Cura Total'), ('partial', 'Cura Parcial')], default='total', max_length=10, verbose_name='Tipo de Cura')),
                ('healing_date', models.DateField(verbose_name='Data da Cura')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healings_recorded', to='website.member', verbose_name='Membro que Registrou')),
                ('word_of_knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healings', to='website.wordofknowledge', verbose_name='Palavra de Conhecimento Relacionada')),
            ],
            options={
                'verbose_name': 'Cura',
                'verbose_name_plural': 'Curas',
                'ordering': ['-healing_date', '-recorded_at'],
            },
        ),
    ]
