# Generated by Django 4.2.16 on 2025-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_member_is_approver_wordofknowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_consolidated',
            field=models.BooleanField(default=False, help_text='Membro já passou pelo processo de consolidação', verbose_name='Está Consolidado'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_discipled',
            field=models.BooleanField(default=False, help_text='Membro já passou pelo processo de discipulado', verbose_name='Está Discipulado'),
        ),
    ]
