# Generated by Django 4.2.16 on 2025-12-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_member_is_consolidated_member_is_discipled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Ex: Fotografia, Gravação, Cultos, Ensaios', max_length=200, verbose_name='Título')),
                ('month', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('name', models.CharField(blank=True, help_text='Nome adicional para a escala (opcional)', max_length=100, null=True, verbose_name='Nome Personalizado')),
                ('color', models.CharField(blank=True, help_text='Cor para identificação visual (ex: #3B82F6)', max_length=7, null=True, verbose_name='Cor')),
                ('use_team_rotation', models.BooleanField(default=False, help_text='Se marcado, usa equipes que se revezam por semana. Se não, atribui membros diretamente aos dias.', verbose_name='Usar Rotação de Equipes')),
                ('guidelines', models.TextField(blank=True, help_text='Instruções e informações importantes para esta escala', null=True, verbose_name='Orientações')),
                ('is_published', models.BooleanField(default=False, help_text='Se publicada, a escala fica visível para os membros', verbose_name='Publicada')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicada em')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='website.ministry', verbose_name='Ministério')),
            ],
            options={
                'verbose_name': 'Escala Mensal',
                'verbose_name_plural': 'Escalas Mensais',
                'ordering': ['-year', '-month', 'ministry__name', 'title'],
                'unique_together': {('ministry', 'title', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Equipe')),
                ('color', models.CharField(default='#3B82F6', help_text='Cor para identificação visual', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='website.member', verbose_name='Líder da Equipe')),
                ('members', models.ManyToManyField(related_name='teams', to='website.member', verbose_name='Membros')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='website.ministry', verbose_name='Ministério')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['ministry__name', 'name'],
                'unique_together': {('ministry', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(blank=True, help_text='Ex: Culto de Quarta, Culto de Domingo, Ensaio', max_length=200, null=True, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Marcar se este dia foi cancelado', verbose_name='Cancelado')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('members', models.ManyToManyField(blank=True, help_text='Membros escalados para este dia', related_name='schedule_days', to='website.member', verbose_name='Membros')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='website.monthlyschedule', verbose_name='Escala')),
                ('team', models.ForeignKey(blank=True, help_text='Equipe escalada para este dia (apenas se usar rotação de equipes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_days', to='website.team', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Dia de Escala',
                'verbose_name_plural': 'Dias de Escala',
                'ordering': ['date'],
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
