# Generated by Django 4.2.16 on 2025-12-08 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_monthlyschedule_team_scheduleday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['name'], 'verbose_name': 'Ministério', 'verbose_name_plural': 'Ministérios'},
        ),
        migrations.AddField(
            model_name='ministry',
            name='color',
            field=models.CharField(default='#F97316', help_text='Cor do ministério em hexadecimal (ex: #F97316)', max_length=7),
        ),
        migrations.AddField(
            model_name='ministry',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ministério Ativo'),
        ),
        migrations.CreateModel(
            name='MinistryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('leader', 'Líder'), ('member', 'Membro')], default='member', max_length=20, verbose_name='Papel no Ministério')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no Ministério')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_memberships', to='website.member')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='website.ministry')),
            ],
            options={
                'verbose_name': 'Membro do Ministério',
                'verbose_name_plural': 'Membros dos Ministérios',
                'ordering': ['-role', 'member__name'],
                'unique_together': {('member', 'ministry')},
            },
        ),
    ]
