# Generated by Django 4.2.16 on 2025-12-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_ministry_options_ministry_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinistrationSchedule',
        ),
    ]
