# Generated by Django 4.2.16 on 2026-03-02 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConflictOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('conflicting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicting_overrides', to='website.monthlyschedule', verbose_name='Escala em Conflito')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_overrides', to='website.member', verbose_name='Membro')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_overrides', to='website.scheduleday', verbose_name='Dia da Escala')),
            ],
            options={
                'verbose_name': 'Override de Conflito',
                'verbose_name_plural': 'Overrides de Conflito',
                'ordering': ['-created_at'],
            },
        ),
    ]
