# Generated by Django 4.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=150, verbose_name='Nome do Autor')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonies/', verbose_name='Foto')),
                ('content', models.TextField(verbose_name='Testemunho')),
                ('category', models.CharField(choices=[('healing', 'Cura'), ('salvation', 'Salvação'), ('deliverance', 'Libertação'), ('provision', 'Provisão'), ('restoration', 'Restauração'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria')),
                ('is_approved', models.BooleanField(default=False, help_text='Testemunho aprovado para exibição no site', verbose_name='Aprovado')),
                ('show_on_home', models.BooleanField(default=False, help_text='Exibir este testemunho na página inicial', verbose_name='Exibir na Home')),
                ('testimony_date', models.DateField(blank=True, null=True, verbose_name='Data do Testemunho')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='website.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Testemunho',
                'verbose_name_plural': 'Testemunhos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
