# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Cole a URL do post/reel do Instagram para embed de vídeo', max_length=500, null=True, verbose_name='URL do Instagram'),
        ),
    ]
