# Generated by Django 4.2.16 on 2026-03-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_delete_canteendebtor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Pedido de oração')),
            ],
            options={
                'verbose_name': 'Pedido de Oração',
                'verbose_name_plural': 'Pedidos de Oração',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'Membro (Sem acesso ao painel)'), ('admin', 'Administrador (Acesso total)'), ('visitors', 'Visitantes (Gerencia visitantes)'), ('consolidation', 'Consolidação (Gerencia acompanhamentos)'), ('events', 'Eventos (Gerencia eventos)')], default='member', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
