# Generated by Django 4.2.16 on 2026-03-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_canteendebtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
