# Generated by Django 5.1.5 on 2026-04-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_remove_member_ministry_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleday',
            name='has_shifts',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, este dia tem escalas separadas para manhã e noite', verbose_name='Tem turnos (Manhã/Noite)'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='members_evening',
            field=models.ManyToManyField(blank=True, related_name='schedule_days_evening', to='website.member', verbose_name='Membros da Noite'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='members_morning',
            field=models.ManyToManyField(blank=True, related_name='schedule_days_morning', to='website.member', verbose_name='Membros da Manhã'),
        ),
    ]
