# Generated by Django 4.2.16 on 2026-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_add_schedule_day_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='tempo',
            field=models.CharField(blank=True, choices=[('rapida', 'Rápida'), ('media', 'Média'), ('lenta', 'Lenta')], default='', max_length=10, verbose_name='Andamento'),
        ),
    ]
