# Generated by Django 4.2.16 on 2026-04-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_add_music_tempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='roteiro/', verbose_name='Foto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de expiração')),
                ('info_adicional', models.TextField(blank=True, verbose_name='Informação adicional')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Anúncio do Roteiro',
                'verbose_name_plural': 'Anúncios do Roteiro',
                'ordering': ['ordem', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(default='Roteiro de Culto', max_length=255)),
            ],
            options={
                'verbose_name': 'Roteiro de Culto',
                'verbose_name_plural': 'Roteiros de Culto',
            },
        ),
        migrations.CreateModel(
            name='AnuncioRoteiroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='website.anuncioroteiro')),
            ],
            options={
                'verbose_name': 'Data do Anúncio',
                'verbose_name_plural': 'Datas do Anúncio',
                'ordering': ['data', 'hora'],
            },
        ),
        migrations.AddField(
            model_name='anuncioroteiro',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='website.roteiro'),
        ),
    ]
