# Generated by Django 4.2.16 on 2026-03-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_anuncioroteiro_roteiro_anuncioroteirodata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioRoteiroFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(upload_to='roteiro/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='website.anuncioroteiro')),
            ],
            options={
                'verbose_name': 'Foto do Anúncio',
                'verbose_name_plural': 'Fotos do Anúncio',
                'ordering': ['ordem', 'created_at'],
            },
        ),
    ]