# Generated by Django 4.2.16 on 2026-05-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_divisionmember_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyschedule',
            options={'ordering': ['-year', '-month', '-start_date', 'ministry__name', 'title'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Apenas para escalas semanais (0=seg … 6=dom)', max_length=13, null=True, verbose_name='Dias da Semana'),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='end_date',
            field=models.DateField(blank=True, help_text='Deixe vazio para vigência indefinida', null=True, verbose_name='Válida até'),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='schedule_type',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('weekly', 'Semanal')], default='monthly', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='start_date',
            field=models.DateField(blank=True, help_text='Primeira semana desta escala semanal', null=True, verbose_name='Válida a partir de'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0=seg … 6=dom. Preenchido apenas em escalas semanais.', null=True, verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='use_team_rotation',
            field=models.BooleanField(default=False, help_text='Se marcado, usa equipes que se revezam. Se não, atribui membros diretamente aos dias.', verbose_name='Usar Rotação de Equipes'),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
