# Generated by Django 4.2.16 on 2026-05-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_schedule_add_weekly_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOfPeace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('family_name', models.CharField(max_length=150, verbose_name='Nome do solicitante')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone para contato')),
                ('address', models.TextField(verbose_name='Endereço completo')),
                ('family_size', models.PositiveIntegerField(verbose_name='Número de membros na família')),
                ('prayer_types', models.CharField(blank=True, default='', help_text='Lista separada por vírgulas dos motivos selecionados', max_length=500, verbose_name='Motivos de oração')),
                ('prayer_description', models.TextField(blank=True, help_text='Descreva com mais detalhes o que deseja oração', null=True, verbose_name='Descrição / pedido de oração')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='available', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Casa de Paz',
                'verbose_name_plural': 'Casas de Paz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testimony',
            name='source',
            field=models.CharField(choices=[('manual', 'Cadastro manual'), ('house_of_peace', 'Casa de Paz')], default='manual', max_length=20, verbose_name='Origem'),
        ),
        migrations.CreateModel(
            name='HouseOfPeaceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'Aceita'), ('scheduled', 'Agendada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='accepted', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Dia marcado para a visita')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True, verbose_name='Breve relato da visita')),
                ('had_healing', models.BooleanField(default=False, verbose_name='Houve cura?')),
                ('healing_description', models.TextField(blank=True, null=True, verbose_name='Descrição da cura')),
                ('had_testimony', models.BooleanField(default=False, verbose_name='Houve testemunho?')),
                ('testimony_description', models.TextField(blank=True, null=True, verbose_name='Descrição do testemunho')),
                ('will_continue', models.BooleanField(default=False, verbose_name='Haverá mais Casas de Paz com essa família?')),
                ('house_of_peace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='website.houseofpeace')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_of_peace_assignments', to='website.member')),
            ],
            options={
                'verbose_name': 'Atribuição de Casa de Paz',
                'verbose_name_plural': 'Atribuições de Casa de Paz',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddField(
            model_name='houseofpeace',
            name='accepted_members',
            field=models.ManyToManyField(blank=True, related_name='houses_of_peace', through='website.HouseOfPeaceAssignment', to='website.member'),
        ),
        migrations.AddField(
            model_name='houseofpeace',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.neighborhood', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='healing',
            name='house_of_peace_assignment',
            field=models.ForeignKey(blank=True, help_text='Caso esta cura tenha sido registrada durante uma Casa de Paz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healings', to='website.houseofpeaceassignment', verbose_name='Atribuição de Casa de Paz'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='house_of_peace_assignment',
            field=models.ForeignKey(blank=True, help_text='Caso este testemunho tenha sido gerado durante uma Casa de Paz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='website.houseofpeaceassignment', verbose_name='Atribuição de Casa de Paz'),
        ),
        migrations.AddIndex(
            model_name='houseofpeaceassignment',
            index=models.Index(fields=['house_of_peace', 'member', 'status'], name='website_hou_house_o_fe4d84_idx'),
        ),
    ]
