# Generated by Django 4.2.16 on 2026-05-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_houseofpeace_testimony_source_houseofpeaceassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='chord_sheet',
            field=models.FileField(blank=True, help_text='(Será descontinuado - use a seção de Cifras abaixo)', null=True, upload_to='chord_sheet/'),
        ),
        migrations.CreateModel(
            name='ChordSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Arquivo PDF da cifra', upload_to='chord_sheet/')),
                ('tone', models.CharField(blank=True, help_text='Ex: Dó, Mi, Sol (opcional)', max_length=50, null=True, verbose_name='Tom')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chordsheets', to='website.music')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
