# Generated by Django 4.2.16 on 2026-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_alter_music_chord_sheet_chordsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chordsheet',
            name='file',
            field=models.FileField(help_text='Arquivo PDF da cifra', max_length=255, upload_to='chord_sheet/'),
        ),
    ]
