# Generated by Django 4.2.16 on 2026-06-01 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models.media_attachment


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_alter_chordsheet_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('content_type', models.CharField(choices=[('artwork', 'Arte'), ('reel', 'Reel'), ('carousel', 'Carrossel'), ('story', 'Story'), ('photography', 'Fotografia'), ('video', 'Vídeo'), ('livestream', 'Transmissão ao Vivo'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('website_banner', 'Banner do Site'), ('devotional', 'Devocional'), ('announcement', 'Comunicado')], max_length=20, verbose_name='Tipo de Conteúdo')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Entrega')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Produção'), ('review', 'Em Revisão'), ('approved', 'Aprovado'), ('scheduled', 'Agendado'), ('published', 'Publicado')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_contents', to='website.event', verbose_name='Evento')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_contents_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Conteúdo de Mídia',
                'verbose_name_plural': 'Conteúdos de Mídia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='Status')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='website.mediacontent', verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Tarefa de Mídia',
                'verbose_name_plural': 'Tarefas de Mídia',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Comentário')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.mediacontent', verbose_name='Conteúdo')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.mediatask', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Comentário de Mídia',
                'verbose_name_plural': 'Comentários de Mídia',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('file', models.FileField(upload_to='media_planning/', validators=[website.models.media_attachment.validate_media_file], verbose_name='Arquivo')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.mediacontent', verbose_name='Conteúdo')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.mediatask', verbose_name='Tarefa')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo de Mídia',
                'verbose_name_plural': 'Anexos de Mídia',
                'ordering': ['-created_at'],
            },
        ),
    ]
