# Generated by Django 4.2.16 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_alter_chordsheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseofpeace',
            name='family_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de membros na família'),
        ),
    ]
