# Generated by Django 4.2.16 on 2026-06-01 13:52

from django.db import migrations


def seed_midia_ministry(apps, schema_editor):
    Ministry = apps.get_model('website', 'Ministry')
    Ministry.objects.get_or_create(
        name='Mídia Externa',
        defaults={
            'description': 'Ministério de Mídia Externa — produção de conteúdo, design e comunicação.',
            'color': '#8B5CF6',
            'is_active': True,
        },
    )


def reverse_seed(apps, schema_editor):
    Ministry = apps.get_model('website', 'Ministry')
    Ministry.objects.filter(name='Mídia Externa').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_mediacontent_mediatask_mediacomment_mediaattachment'),
    ]

    operations = [
        migrations.RunPython(seed_midia_ministry, reverse_seed),
    ]
