# Generated by Django 4.2.16 on 2026-06-17 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'Membro (Sem acesso ao painel)'), ('admin', 'Administrador (Acesso total)'), ('visitors', 'Visitantes (Gerencia visitantes)'), ('consolidation', 'Consolidação (Gerencia acompanhamentos)'), ('events', 'Eventos (Gerencia eventos)'), ('prosperar', 'Prosperar (Area de empresas)')], default='member', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.CreateModel(
            name='ProsperarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=180, verbose_name='Nome da empresa')),
                ('business_sector', models.CharField(choices=[('food', 'Alimentacao'), ('beauty', 'Beleza e estetica'), ('health', 'Saude e bem-estar'), ('education', 'Educacao'), ('tech', 'Tecnologia'), ('fashion', 'Moda e acessorios'), ('construction', 'Construcao e reformas'), ('automotive', 'Automotivo'), ('finance', 'Financas e consultoria'), ('home', 'Casa e decoracao'), ('services', 'Servicos gerais'), ('other', 'Outro')], max_length=30, verbose_name='Ramo de atividade')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='prosperar_logos/', verbose_name='Logo da empresa')),
                ('address', models.TextField(verbose_name='Endereco')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone / WhatsApp')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Link do Instagram')),
                ('status', models.CharField(choices=[('pending', 'Pendente de aprovacao'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Empresa em destaque')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prosperar_companies', to='website.neighborhood', verbose_name='Bairro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prosperar_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa Prosperar',
                'verbose_name_plural': 'Empresas Prosperar',
                'ordering': ['company_name'],
            },
        ),
    ]
