# Generated by Django 4.2.16 on 2026-06-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_seed_midia_ministry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('content_type', models.CharField(choices=[('artwork', 'Arte'), ('reel', 'Reel'), ('carousel', 'Carrossel'), ('story', 'Story'), ('photography', 'Fotografia'), ('video', 'Vídeo'), ('livestream', 'Transmissão ao Vivo'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('website_banner', 'Banner do Site'), ('devotional', 'Devocional'), ('announcement', 'Comunicado')], max_length=20, verbose_name='Tipo padrão')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Conteúdo',
                'verbose_name_plural': 'Categorias de Conteúdo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaMonthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('categories', models.ManyToManyField(blank=True, related_name='month_plans', to='website.mediacontentcategory', verbose_name='Categorias')),
                ('events', models.ManyToManyField(blank=True, related_name='month_plans', to='website.event', verbose_name='Eventos')),
            ],
            options={
                'verbose_name': 'Plano Mensal de Mídia',
                'verbose_name_plural': 'Planos Mensais de Mídia',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='website.mediacontentcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='month_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='website.mediamonthplan', verbose_name='Plano Mensal'),
        ),
    ]
