# Generated by Django 4.2.16 on 2026-06-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_alter_user_user_type_prosperarcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosperarcompany',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prosperar_companies', to='website.member', verbose_name='Membro vinculado'),
        ),
    ]
