# Generated by Django 5.0 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_prosperarcompany_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='church_role',
            field=models.CharField(
                choices=[
                    ('member', 'Membro'),
                    ('pastor', 'Pastor(a)'),
                    ('elder', 'Presbítero(a)'),
                    ('deacon', 'Diácono(a)'),
                    ('leader', 'Líder'),
                ],
                default='member',
                help_text='Função ministerial do membro, independente das permissões de acesso.',
                max_length=20,
                verbose_name='Função na igreja',
            ),
        ),
    ]
