# Generated by Django 4.2.16 on 2026-08-03 04:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models.external_media


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_prosperarcompany_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMediaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('original_video', models.FileField(upload_to=website.models.external_media.external_media_upload_path)),
                ('original_language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], default='pt', max_length=10)),
                ('output_languages', models.JSONField(default=website.models.external_media.default_output_languages)),
                ('translation_model', models.CharField(default='gpt-4.1-mini', max_length=100)),
                ('status', models.CharField(choices=[('UPLOADING', 'Enviando vídeo'), ('PENDING', 'Na fila'), ('EXTRACTING_AUDIO', 'Extraindo áudio'), ('TRANSCRIBING', 'Transcrevendo'), ('GENERATING_SUBTITLES', 'Gerando legendas'), ('TRANSLATING', 'Traduzindo'), ('AWAITING_REVIEW', 'Aguardando revisão'), ('RENDERING', 'Renderizando vídeos'), ('FINISHED', 'Finalizado'), ('ERROR', 'Erro'), ('CANCELLED', 'Cancelado')], default='UPLOADING', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=180)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Processamento de mídia externa',
                'verbose_name_plural': 'Processamentos de mídia externa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('source_language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], default='pt', max_length=10)),
                ('target_language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], default='en', max_length=10)),
                ('source_text', models.CharField(max_length=255)),
                ('translated_text', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Termo do glossário',
                'verbose_name_plural': 'Glossário de mídia externa',
                'ordering': ['source_text'],
            },
        ),
        migrations.CreateModel(
            name='RenderPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('video_codec', models.CharField(default='libx264', max_length=30)),
                ('audio_codec', models.CharField(default='aac', max_length=30)),
                ('video_crf', models.PositiveSmallIntegerField(default=20)),
                ('extra_ffmpeg_args', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Preset de renderização',
                'verbose_name_plural': 'Presets de renderização',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('font_name', models.CharField(default='Arial', max_length=100)),
                ('font_size', models.PositiveIntegerField(default=48)),
                ('primary_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('outline_color', models.CharField(default='#000000', max_length=10)),
                ('outline_width', models.PositiveIntegerField(default=3)),
                ('shadow', models.PositiveIntegerField(default=1)),
                ('margin_bottom', models.PositiveIntegerField(default=60)),
                ('alignment', models.PositiveSmallIntegerField(default=2)),
                ('max_lines', models.PositiveSmallIntegerField(default=2)),
                ('max_characters', models.PositiveSmallIntegerField(default=42)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estilo de legenda',
                'verbose_name_plural': 'Estilos de legenda',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ministry',
            name='code',
            field=models.SlugField(blank=True, help_text='Código estável usado por permissões internas (ex: midia_externa).', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SubtitleTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], max_length=10)),
                ('is_source', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_tracks', to='website.externalmediajob')),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cue_index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_ms', models.PositiveBigIntegerField()),
                ('end_ms', models.PositiveBigIntegerField()),
                ('text', models.TextField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='website.subtitletrack')),
            ],
            options={
                'ordering': ['cue_index'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('VIDEO', 'Vídeo renderizado'), ('SRT', 'Legenda SRT'), ('VTT', 'Legenda VTT')], max_length=20)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], max_length=10)),
                ('file', models.FileField(upload_to=website.models.external_media.external_media_asset_path)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.externalmediajob')),
            ],
            options={
                'ordering': ['language', 'kind'],
            },
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(fields=('source_language', 'target_language', 'source_text'), name='unique_external_media_glossary_term'),
        ),
        migrations.AddField(
            model_name='externalmediajob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_media_jobs', to='website.member'),
        ),
        migrations.AddField(
            model_name='externalmediajob',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='website.renderpreset'),
        ),
        migrations.AddField(
            model_name='externalmediajob',
            name='subtitle_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='website.subtitlestyle'),
        ),
        migrations.AddConstraint(
            model_name='subtitletrack',
            constraint=models.UniqueConstraint(fields=('job', 'language'), name='unique_job_subtitle_language'),
        ),
        migrations.AddConstraint(
            model_name='subtitlecue',
            constraint=models.UniqueConstraint(fields=('track', 'cue_index'), name='unique_track_cue_index'),
        ),
        migrations.AddConstraint(
            model_name='subtitlecue',
            constraint=models.CheckConstraint(check=models.Q(('end_ms__gt', models.F('start_ms'))), name='cue_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('job', 'kind', 'language'), name='unique_job_asset_kind_language'),
        ),
        migrations.AddIndex(
            model_name='externalmediajob',
            index=models.Index(fields=['created_by', '-created_at'], name='website_ext_created_1aa9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmediajob',
            index=models.Index(fields=['status'], name='website_ext_status_7bdbc9_idx'),
        ),
    ]
