# Generated by Django 4.2.16 on 2026-08-03 04:07

from django.db import migrations, models
import website.models.external_media


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_seed_external_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalmediajob',
            name='original_video',
            field=models.FileField(storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_upload_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_asset_path),
        ),
    ]
