# Generated by Django 4.2.16 on 2026-08-03 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models.external_media


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_optimize_external_media_render_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMediaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Em preparação'), ('PENDING', 'Na fila'), ('ASSEMBLING', 'Montando vídeo'), ('PROCESSING', 'Processando'), ('AWAITING_REVIEW', 'Aguardando revisão'), ('FINISHED', 'Finalizado'), ('ERROR', 'Erro'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=180)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_media_projects', to='website.member')),
                ('render_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='website.externalmediajob')),
            ],
            options={
                'verbose_name': 'Projeto de mídia',
                'verbose_name_plural': 'Projetos de mídia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('ANNOUNCEMENT', 'Anúncios'), ('STORIES', 'Stories'), ('TRANSLATION', 'Tradução'), ('REELS', 'Reels'), ('TESTIMONY', 'Testemunhos'), ('OTHER', 'Outros')], default='OTHER', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_template_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template de mídia',
                'verbose_name_plural': 'Templates de mídia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaTemplateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('allows_multiple', models.BooleanField(default=False)),
                ('min_occurrences', models.PositiveSmallIntegerField(default=1)),
                ('max_occurrences', models.PositiveSmallIntegerField(default=1)),
                ('default_video', models.FileField(blank=True, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_template_path)),
            ],
            options={
                'verbose_name': 'Bloco do template',
                'verbose_name_plural': 'Blocos do template',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Executando'), ('FINISHED', 'Concluído'), ('SKIPPED', 'Ignorado'), ('ERROR', 'Erro')], default='PENDING', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='website.externalmediaproject')),
            ],
            options={
                'verbose_name': 'Etapa do pipeline',
                'verbose_name_plural': 'Etapas do pipeline',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBlockMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_project_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_project_upload_path)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_media', to='website.mediatemplateblock')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_media', to='website.externalmediaproject')),
            ],
            options={
                'verbose_name': 'Vídeo de bloco',
                'verbose_name_plural': 'Vídeos dos blocos',
                'ordering': ['block__order', 'position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MediaTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=16)),
                ('changelog', models.TextField(blank=True)),
                ('original_language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], default='pt', max_length=10)),
                ('output_languages', models.JSONField(default=website.models.external_media.default_output_languages)),
                ('default_settings', models.JSONField(blank=True, default=dict)),
                ('allowed_overrides', models.JSONField(blank=True, default=list)),
                ('intro_video', models.FileField(blank=True, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_template_path)),
                ('outro_video', models.FileField(blank=True, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_template_path)),
                ('lut_file', models.FileField(blank=True, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_template_path)),
                ('music_file', models.FileField(blank=True, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_template_path)),
                ('music_volume', models.DecimalField(decimal_places=2, default=0.15, max_digits=4)),
                ('fade_in_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fade_out_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_versions', to='website.renderpreset')),
                ('subtitle_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_versions', to='website.subtitlestyle')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='website.mediatemplate')),
            ],
            options={
                'verbose_name': 'Versão de template',
                'verbose_name_plural': 'Versões de templates',
                'ordering': ['template__name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='MediaTemplatePlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('silence_removal', 'Corte de silêncio'), ('filler_removal', 'Remover muletas'), ('auto_tracking', 'Centralizar apresentador'), ('subtitle_pt', 'Legenda PT'), ('translation_en', 'Tradução EN'), ('lut', 'Aplicar LUT'), ('intro', 'Intro'), ('outro', 'Tela final'), ('music', 'Música')], max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user_can_override', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='website.mediatemplateversion')),
            ],
            options={
                'verbose_name': 'Plugin do template',
                'verbose_name_plural': 'Plugins do template',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='mediatemplateblock',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='website.mediatemplateversion'),
        ),
        migrations.AddField(
            model_name='externalmediaproject',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='website.mediatemplateversion'),
        ),
        migrations.AddConstraint(
            model_name='projectpipelinestep',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_project_pipeline_step'),
        ),
        migrations.AddConstraint(
            model_name='projectblockmedia',
            constraint=models.UniqueConstraint(fields=('project', 'block', 'position'), name='unique_project_block_media_position'),
        ),
        migrations.AddConstraint(
            model_name='mediatemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_media_template_version'),
        ),
        migrations.AddConstraint(
            model_name='mediatemplateplugin',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_media_template_plugin'),
        ),
        migrations.AddConstraint(
            model_name='mediatemplateblock',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='unique_media_template_block_key'),
        ),
        migrations.AddIndex(
            model_name='externalmediaproject',
            index=models.Index(fields=['created_by', '-created_at'], name='website_ext_created_cc3b64_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmediaproject',
            index=models.Index(fields=['status'], name='website_ext_status_a46e3c_idx'),
        ),
    ]
