# Generated by Django 4.2.16 on 2026-08-11 01:30

from django.db import migrations, models
import django.db.models.deletion


def seed_church_pa_profile(apps, schema_editor):
    MasteringProfile = apps.get_model('website', 'MasteringProfile')
    MasteringProfile.objects.get_or_create(
        code='church_pa',
        defaults={
            'name': 'PA Igreja',
            'target_lufs': -16.0,
            'true_peak_db': -1.0,
            'bus_compression_enabled': False,
            'limiter_enabled': True,
            'is_active': True,
            'is_default': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_backgroundmusictrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('target_lufs', models.DecimalField(decimal_places=1, default=-16.0, max_digits=4, verbose_name='Loudness alvo (LUFS)')),
                ('true_peak_db', models.DecimalField(decimal_places=1, default=-1.0, max_digits=4, verbose_name='True Peak máximo (dBTP)')),
                ('bus_compression_enabled', models.BooleanField(default=False, verbose_name='Compressão de bus leve')),
                ('limiter_enabled', models.BooleanField(default=True, verbose_name='Limiter de true peak')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Perfil padrão')),
            ],
            options={
                'verbose_name': 'Perfil de masterização',
                'verbose_name_plural': 'Perfis de masterização',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='audio_ducking_enabled',
            field=models.BooleanField(default=True, verbose_name='Ducking automático'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='audio_mastering_enabled',
            field=models.BooleanField(default=False, verbose_name='Masterização'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='audio_mixing_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuração avançada de mixagem'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='audio_mixing_enabled',
            field=models.BooleanField(default=False, verbose_name='Mixagem inteligente'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='audio_spectral_ducking_enabled',
            field=models.BooleanField(default=False, verbose_name='Ducking espectral'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='mastering_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_versions', to='website.masteringprofile', verbose_name='Perfil de masterização'),
        ),
        migrations.RunPython(seed_church_pa_profile, migrations.RunPython.noop),
    ]
