# Generated by Django 4.2.16 on 2026-08-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_audio_mixing_mastering'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatemplateversion',
            name='dialogue_processing_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuração avançada de tratamento de diálogo'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='dialogue_processing_enabled',
            field=models.BooleanField(default=False, verbose_name='Tratamento de diálogo'),
        ),
    ]
