# Generated by Django 4.2.16 on 2026-08-30 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models.external_media


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_project_custom_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(db_index=True, editable=False, max_length=12)),
                ('languages', models.JSONField(default=list)),
                ('base_revisions', models.JSONField(default=dict)),
                ('reviewer_name', models.CharField(blank=True, max_length=120)),
                ('reviewer_contact', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Em andamento'), ('SUBMITTED', 'Aguardando aprovação'), ('UNDER_REVIEW', 'Em análise'), ('APPROVED', 'Aprovada'), ('PARTIALLY_APPROVED', 'Aprovada parcialmente'), ('REJECTED', 'Rejeitada')], default='DRAFT', max_length=24)),
                ('general_comment', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('first_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('preview_file', models.FileField(blank=True, max_length=255, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.subtitle_review_preview_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_subtitle_review_sessions', to='website.member')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_review_sessions', to='website.externalmediajob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_review_sessions', to='website.externalmediaproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='human_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='subtitle_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='translation_status',
            field=models.CharField(choices=[('CURRENT', 'Atualizada'), ('SOURCE_CHANGED', 'Texto original alterado')], default='CURRENT', max_length=24),
        ),
        migrations.CreateModel(
            name='SubtitleVideoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('subtitle_revisions', models.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_video_versions', to='website.externalmediajob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_video_versions', to='website.externalmediaproject')),
                ('review_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_versions', to='website.subtitlereviewsession')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], max_length=10)),
                ('base_track_revision', models.PositiveIntegerField(default=1)),
                ('original_text', models.TextField()),
                ('suggested_text', models.TextField()),
                ('resolved_text', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada'), ('CONFLICT', 'Conflito')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_suggestions', to='website.subtitlecue')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_subtitle_suggestions', to='website.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='website.subtitlereviewsession')),
            ],
            options={
                'ordering': ['language', 'cue__cue_index'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('cues_snapshot', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtitle_revisions', to='website.member')),
                ('review_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_revisions', to='website.subtitlereviewsession')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='website.subtitletrack')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtitle_review_events', to='website.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.subtitlereviewsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subtitlevideoversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_project_subtitle_video_version'),
        ),
        migrations.AddConstraint(
            model_name='subtitlesuggestion',
            constraint=models.UniqueConstraint(fields=('session', 'cue'), name='unique_review_session_cue'),
        ),
        migrations.AddConstraint(
            model_name='subtitlerevision',
            constraint=models.UniqueConstraint(fields=('track', 'revision'), name='unique_subtitle_track_revision'),
        ),
        migrations.AddIndex(
            model_name='subtitlereviewsession',
            index=models.Index(fields=['project', 'status'], name='website_sub_project_2f5b72_idx'),
        ),
        migrations.AddIndex(
            model_name='subtitlereviewsession',
            index=models.Index(fields=['expires_at'], name='website_sub_expires_7fbc3b_idx'),
        ),
    ]
