# Generated by Django 4.2.16 on 2026-08-30 16:52

from django.db import migrations, models
import django.db.models.deletion
import website.models.external_media


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_subtitlereviewsession_subtitletrack_human_reviewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleVideoVersionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('VIDEO', 'Vídeo renderizado'), ('SRT', 'Legenda SRT'), ('VTT', 'Legenda VTT')], max_length=20)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('it', 'Italiano')], max_length=10)),
                ('file', models.FileField(max_length=255, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.subtitle_video_version_asset_path)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.subtitlevideoversion')),
            ],
            options={
                'ordering': ['language', 'kind'],
            },
        ),
        migrations.AddConstraint(
            model_name='subtitlevideoversionasset',
            constraint=models.UniqueConstraint(fields=('version', 'kind', 'language'), name='unique_subtitle_video_version_asset'),
        ),
    ]
