# Generated by Django 4.2.16 on 2026-08-31 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import website.models.external_media


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_colorlut_default_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('position_ms', models.PositiveBigIntegerField(default=0)),
                ('reviewed_decision_ids', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('ui_state', models.JSONField(blank=True, default=dict)),
                ('undo_stack', models.JSONField(blank=True, default=list)),
                ('redo_stack', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_width', models.PositiveSmallIntegerField(default=960)),
                ('fps', models.PositiveSmallIntegerField(default=30)),
                ('video_crf', models.PositiveSmallIntegerField(default=27)),
                ('audio_bitrate_kbps', models.PositiveSmallIntegerField(default=96)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil de proxy',
                'verbose_name_plural': 'Perfis de proxy',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='externalmediajob',
            name='rendered_from_timeline_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalmediaproject',
            name='final_render_outdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalmediaproject',
            name='preview_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalmediaprojectexport',
            name='timeline_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='interactive_preview_enabled',
            field=models.BooleanField(default=True, verbose_name='Preview interativo'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='preview_confidence_thresholds',
            field=models.JSONField(blank=True, default=website.models.external_media.default_preview_confidence_thresholds),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='preview_editable_capabilities',
            field=models.JSONField(blank=True, default=website.models.external_media.default_preview_capabilities),
        ),
        migrations.CreateModel(
            name='TimelineRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('timeline', models.JSONField(default=dict)),
                ('source_manifest', models.JSONField(default=dict)),
                ('edit_decision_set', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timeline_revisions', to='website.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.timelinerevision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_revisions', to='website.externalmediaproject')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='TimelineMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('inverse_payload', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_mutations', to='website.member')),
                ('from_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.timelinerevision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_mutations', to='website.externalmediaproject')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations', to='website.previewsession')),
                ('to_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.timelinerevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSourceProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=160)),
                ('source_storage_name', models.CharField(max_length=500)),
                ('proxy_file', models.FileField(blank=True, max_length=500, storage=website.models.external_media.get_external_media_storage, upload_to=website.models.external_media.external_media_source_proxy_path)),
                ('status', models.CharField(choices=[('PENDING', 'Preparando'), ('READY', 'Pronto'), ('ERROR', 'Erro')], default='PENDING', max_length=16)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_proxies', to='website.proxyprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_proxies', to='website.externalmediaproject')),
            ],
            options={
                'ordering': ['source_id'],
            },
        ),
        migrations.AddField(
            model_name='previewsession',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.timelinerevision'),
        ),
        migrations.AddField(
            model_name='previewsession',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media_preview_sessions', to='website.member'),
        ),
        migrations.AddField(
            model_name='previewsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_sessions', to='website.externalmediaproject'),
        ),
        migrations.AddField(
            model_name='externalmediaproject',
            name='approved_timeline_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to='website.timelinerevision'),
        ),
        migrations.AddField(
            model_name='externalmediaproject',
            name='current_timeline_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.timelinerevision'),
        ),
        migrations.AddField(
            model_name='mediatemplateversion',
            name='preview_proxy_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_versions', to='website.proxyprofile'),
        ),
        migrations.AddConstraint(
            model_name='timelinerevision',
            constraint=models.UniqueConstraint(fields=('project', 'revision'), name='unique_project_timeline_revision'),
        ),
        migrations.AddConstraint(
            model_name='projectsourceproxy',
            constraint=models.UniqueConstraint(fields=('project', 'source_id', 'profile'), name='unique_project_source_proxy_profile'),
        ),
        migrations.AddConstraint(
            model_name='previewsession',
            constraint=models.UniqueConstraint(fields=('project', 'member'), name='unique_project_member_preview_session'),
        ),
    ]
