# Generated by Django 4.2.16 on 2026-09-17

from django.db import migrations, models


CONTENT_TYPE_CHOICES = [
    ('artwork', 'Arte'),
    ('reel', 'Reel'),
    ('carousel', 'Carrossel'),
    ('story', 'Story'),
    ('photography', 'Fotografia'),
    ('video', 'Vídeo'),
    ('livestream', 'Transmissão ao Vivo'),
    ('youtube', 'YouTube'),
    ('whatsapp', 'WhatsApp'),
    ('website_banner', 'Banner do Site'),
    ('devotional', 'Devocional'),
    ('announcement', 'Comunicado'),
    ('coordination', 'Organização'),
    ('contact', 'Contato'),
    ('approval', 'Aprovação'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0101_merge_media_planning_and_external_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='content_type',
            field=models.CharField(choices=CONTENT_TYPE_CHOICES, max_length=20, verbose_name='Tipo de Conteúdo'),
        ),
        migrations.AlterField(
            model_name='mediacontentcategory',
            name='content_type',
            field=models.CharField(choices=CONTENT_TYPE_CHOICES, max_length=20, verbose_name='Tipo padrão'),
        ),
        migrations.AlterField(
            model_name='mediaplanningtemplateitem',
            name='content_type',
            field=models.CharField(choices=CONTENT_TYPE_CHOICES, max_length=20, verbose_name='Tipo de conteúdo'),
        ),
    ]
