# Generated by Django 4.2.16 on 2026-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0103_ministry_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de término'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='due_date_auto',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='due_offset_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='publication_date_auto',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='publication_offset_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início previsto'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='start_date_auto',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='start_offset_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
