# Generated by Django 4.2.16 on 2026-09-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_media_event_organization_removed_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatask',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Tarefa de Mídia', 'verbose_name_plural': 'Tarefas de Mídia'},
        ),
    ]
