"""
Django settings for connect project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9f)9^dz(mzjv#gr#&ocp8fw0p$d$6h5@a@#4fn99*6!k8(u0_k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DOMAIN = os.getenv('DOMAIN')

ALLOWED_HOSTS = ['0.0.0.0', '192.168.0.108', 'localhost', '127.0.0.1', DOMAIN, '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'website'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'website.middleware.MessageCleanupMiddleware',  # Custom middleware para limpar mensagens
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'connect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.member_module_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'connect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "external_media": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": os.path.join(BASE_DIR, 'media'),
            "base_url": "/media/",
        },
    },
}

AUTH_USER_MODEL = 'website.User'

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/redirect-after-login/'
LOGOUT_REDIRECT_URL = '/login/'

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Email configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'localhost:8000')

# OpenAI (texto + transcrição de arquivos). O tradutor ao vivo continua usando
# Azure Speech; o modelo de texto deve ser escolhido por cada fluxo/view.
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_TRANSCRIPTION_MODEL = os.getenv(
    'OPENAI_TRANSCRIPTION_MODEL',
    'whisper-1',
)

# Mídia Externa. O modelo de tradução é escolhido pelo fluxo que usa AIService;
# apenas o modelo de transcrição é centralizado na variável acima.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', os.getenv('REDIS_URL', 'redis://redis:6379/1'))
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', 21600))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', 21000))
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
EXTERNAL_MEDIA_MAX_UPLOAD_MB = int(os.getenv('EXTERNAL_MEDIA_MAX_UPLOAD_MB', 10240))
EXTERNAL_MEDIA_AUDIO_CHUNK_SECONDS = int(os.getenv('EXTERNAL_MEDIA_AUDIO_CHUNK_SECONDS', 1200))
EXTERNAL_MEDIA_TRANSLATION_BATCH_SIZE = int(os.getenv('EXTERNAL_MEDIA_TRANSLATION_BATCH_SIZE', 40))
EXTERNAL_MEDIA_FFMPEG_TIMEOUT = int(os.getenv('EXTERNAL_MEDIA_FFMPEG_TIMEOUT', 21600))
EXTERNAL_MEDIA_FFMPEG_PRESET = os.getenv('EXTERNAL_MEDIA_FFMPEG_PRESET', 'veryfast')
EXTERNAL_MEDIA_RENDER_PRESET = os.getenv('EXTERNAL_MEDIA_RENDER_PRESET', 'superfast')
EXTERNAL_MEDIA_INTERMEDIATE_PRESET = os.getenv('EXTERNAL_MEDIA_INTERMEDIATE_PRESET', 'superfast')
EXTERNAL_MEDIA_INTERMEDIATE_CRF = int(os.getenv('EXTERNAL_MEDIA_INTERMEDIATE_CRF', 22))
# Mantém a renderização final rápida em máquinas multi-core sem abrir encodes
# demais e deixar o computador sem responsividade.
EXTERNAL_MEDIA_ASSEMBLY_WORKERS = int(os.getenv('EXTERNAL_MEDIA_ASSEMBLY_WORKERS', 2))
EXTERNAL_MEDIA_PROXY_WIDTH = int(os.getenv('EXTERNAL_MEDIA_PROXY_WIDTH', 854))
EXTERNAL_MEDIA_PROXY_CRF = int(os.getenv('EXTERNAL_MEDIA_PROXY_CRF', 30))
EXTERNAL_MEDIA_PROXY_PRESET = os.getenv('EXTERNAL_MEDIA_PROXY_PRESET', 'ultrafast')
EXTERNAL_MEDIA_AUTO_REFRAME_INTERVAL_FRAMES = int(
    os.getenv('EXTERNAL_MEDIA_AUTO_REFRAME_INTERVAL_FRAMES', 10)
)
EXTERNAL_MEDIA_AUTO_REFRAME_MAX_ANALYSIS_WIDTH = int(
    os.getenv('EXTERNAL_MEDIA_AUTO_REFRAME_MAX_ANALYSIS_WIDTH', 640)
)
EXTERNAL_MEDIA_DIARIZATION_ENABLED = os.getenv(
    'EXTERNAL_MEDIA_DIARIZATION_ENABLED', 'True',
).lower() in {'1', 'true', 'yes', 'on'}
EXTERNAL_MEDIA_DIARIZATION_MODEL = os.getenv(
    'EXTERNAL_MEDIA_DIARIZATION_MODEL', 'pyannote/speaker-diarization-community-1',
)
EXTERNAL_MEDIA_DIARIZATION_DEVICE = os.getenv('EXTERNAL_MEDIA_DIARIZATION_DEVICE', 'auto')
HUGGINGFACE_TOKEN = os.getenv('HUGGINGFACE_TOKEN', os.getenv('HF_TOKEN', ''))
EXTERNAL_MEDIA_TASK_LOCK_NAMESPACE = int(os.getenv('EXTERNAL_MEDIA_TASK_LOCK_NAMESPACE', 73421))
FFMPEG_BINARY = os.getenv('FFMPEG_BINARY', 'ffmpeg')
FFPROBE_BINARY = os.getenv('FFPROBE_BINARY', 'ffprobe')

# Configuração de arquivos de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Garante que os diretórios de mídia existam
os.makedirs(os.path.join(MEDIA_ROOT, 'avatars'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'event_banners'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'profile_pictures'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'prosperar_logos'), exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REDIS_URL = os.getenv('REDIS_URL')

if REDIS_URL:
    print("✅ CONFIGURANDO CHANNEL LAYER COM REDIS...")
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    print("⚠️ ATENÇÃO: REDIS_URL não encontrada. Usando InMemoryChannelLayer para desenvolvimento.")
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        },
    }

# AWS S3 Configuration
USE_S3 = os.getenv('USE_S3', 'FALSE').upper() == 'TRUE'

if USE_S3:
    print("✅ CONFIGURANDO S3 PARA ARMAZENAMENTO DE MÍDIA...")
    INSTALLED_APPS.append('storages')
    
    # AWS settings
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_DEFAULT_ACL = None  # Não usar ACLs para evitar o erro AccessControlListNotSupported
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    S3_USE_SIGV4 = True  # Usar a assinatura v4 para solicitações
    
    # Configurações adicionais para resolver problemas de CORS
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')  # Região do bucket
    AWS_QUERYSTRING_AUTH = False  # Desabilitar assinatura de URLs (melhor para CDN)
    
    # S3 media settings
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        'OPTIONS': {
            'location': 'media',
            'file_overwrite': False,
            'default_acl': None,  # Não definir ACL nos arquivos
            'querystring_auth': False,  # Não usar query string auth nas URLs
        }
    }
    STORAGES['external_media'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        'OPTIONS': {
            'location': 'private_media',
            'file_overwrite': False,
            'default_acl': None,
            'querystring_auth': True,
        },
    }
    
    # Override MEDIA_URL when using S3
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    
    print(f"✅ MEDIA FILES WILL BE STORED AT: {MEDIA_URL}")
else:
    print("⚠️ USANDO ARMAZENAMENTO LOCAL PARA MÍDIA. Configure USE_S3=TRUE para usar Amazon S3.")
