# Generated by Django 4.2.16 on 2025-04-03 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evangelism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('evangelism_date', models.DateField(auto_now_add=True)),
                ('conversion', models.CharField(choices=[('new_convert', 'Novo Convertido'), ('reconciled', 'Reconciliado'), ('from_another_church', 'Vindo de outra Igreja')], max_length=20)),
                ('prayer_request', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('conversion', models.CharField(choices=[('new_convert', 'Novo Convertido'), ('reconciled', 'Reconciliado'), ('from_another_church', 'Vindo de outra Igreja')], max_length=20)),
                ('prayer_request', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('conversion', models.CharField(blank=True, choices=[('new_convert', 'Novo Convertido'), ('reconciled', 'Reconciliado'), ('from_another_church', 'Vindo de outra Igreja')], max_length=20, null=True)),
                ('prayer_request', models.TextField(blank=True, null=True)),
                ('is_consolidator', models.BooleanField(default=False)),
                ('is_consolidated', models.BooleanField(default=False)),
                ('is_discipler', models.BooleanField(default=False)),
                ('is_discipled', models.BooleanField(default=False)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ministry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'Em Progresso'), ('completed', 'Completo')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discipled_consolidated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_followups', to='website.member')),
                ('discipler_consolidator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_followups', to='website.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
