# Generated by Django 4.2.16 on 2025-05-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_visitor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='conversion',
            field=models.CharField(blank=True, choices=[('new_convert', 'Novo Convertido'), ('reconciled', 'Reconciliado'), ('from_another_church', 'Vindo de outra Igreja')], max_length=20, null=True),
        ),
    ]
