# Generated by Django 4.2.16 on 2026-03-02 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_visitor_wants_home_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(verbose_name='Data da Escala')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('override_conflict', models.BooleanField(default=False, help_text='Indica que um conflito foi detectado e o usuário optou por prosseguir.', verbose_name='Conflito ignorado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='website.member', verbose_name='Membro')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='website.ministry', verbose_name='Ministério')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Override por')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['-scheduled_date', 'member'],
                'indexes': [models.Index(fields=['member', 'scheduled_date'], name='idx_member_date')],
            },
        ),
    ]
