# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_visitor_wants_home_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Título da escala (ex: Louvor, Portaria, etc)', max_length=200)),
                ('date', models.DateField(help_text='Data da escala')),
                ('description', models.TextField(blank=True, help_text='Descrição adicional da escala', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Horário de início', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Horário de fim', null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Se a pessoa confirmou participação')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='website.member')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='website.ministry')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]