from website.views.media_planning.operations import MediaEventsView, MediaDemandsView, MediaEventRemoveFromMediaView, MediaEventUpdateView
from .views import ministry_organization as ministry_org
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from .views.media_planning import (
    MediaDashboardView,
    MediaMonthPlanCreateView,
    MediaMonthPlanDetailView,
    MediaMonthPlanWizardView,
    MediaPlanToggleEventView,
    MediaPlanToggleCategoryView,
    MediaContentCategoryCreateView,
    MediaPlanCreateEventView,
    MediaPlanMacroEventView,
    MediaPlanMacroCategoryView,
    MediaEventContentsView,
    MediaCategoryContentsView,
    MediaContentListView,
    MediaDemandsPanelView,
    MediaDemandQuickCreateView,
    MediaDemandQuickUpdateView,
    MediaEventQuickCreateView,
    MediaEventSuggestionsView,
    MediaEventTypeQuickCreateView,
    MediaContentCreateView,
    MediaContentUpdateView,
    MediaContentDeleteView,
    MediaTaskCreateView,
    MediaTaskUpdateStatusView,
    MediaTaskUpdateDescriptionView,
    MediaCommentCreateView,
    MediaAttachmentCreateView,
    MediaCalendarView,
    MediaCalendarEventsAPIView,
    MediaCalendarUpdateView,
    MediaEventTypeListView,
    MediaEventTypeCreateView,
    MediaEventTypeUpdateView,
    MediaEventTypeDeleteView,
    MediaTemplateListView,
    MediaTemplateCreateView,
    MediaTemplateSetupView,
    MediaTemplateDetailView,
    MediaTemplateUpdateView,
    MediaTemplateItemCreateView,
    MediaTemplateItemUpdateView,
    MediaTemplateItemDeleteView,
    MediaEventSetTypeView,
    MediaApplyTemplateView,
    MediaOrganizationDashboardView,
    MediaSubTeamListView,
    MediaSubTeamCreateView,
    MediaSubTeamDetailView,
    MediaSubTeamUpdateView,
    MediaSubTeamMemberAddView,
    MediaSubTeamMemberUpdateView,
    MediaSubTeamMemberRemoveView,
    MediaRoleListView,
    MediaRoleCreateView,
    MediaLeadershipListView,
    MediaLeadershipCreateView,
    MediaLeadershipUpdateView,
    MediaResourceListView,
    MediaResourceCreateView,
    MediaResourceDetailView,
    MediaResourceUpdateView,
    MediaResourceCredentialUpdateView,
    MediaResourceCredentialRevealView,
)
from .views.music import MusicListView, MusicCreateView, MusicDeleteView, MusicUpdateView, MusicUserListView
from .views.home import HomeView, TestimonyListView, ContactView
from .views.visitor import VisitorCreateView, MemberVisitorCreateView, MemberVisitorListView, PastoralVisitorListView, PastoralVisitorReportView
from .views.evangelism import EvangelismCreateView, EvangelismListView
from .views.member import (
    MemberCreateView,
    NewConvertsListView,
    MemberConsolidationListView,
    MemberConsolidationDetailView,
    MemberConsolidationReportView,
    ConsolidatorGuideView,
    ConsolidatorAssignmentsView,
    RequestConsolidationView,
)
from .views.translator import AudioRecorderView, TranscriptionDisplayView
from .views.event import EventDetailView, EventListView
from .views.member_auth import (
    MemberLoginView, MemberDashboardView, MemberLogoutView, MemberProfileView,
    MemberApproveWordView, MemberRejectWordView,
    MemberRoteiroView,
    RedirectAfterLoginView,
)
from .views.member_schedule import MemberScheduleDetailView
from .views.user_management import (
    UserManagementView,
    ResetUserPasswordView,
    DeleteUserView,
    UserEditView,
    ChangePasswordView,
)
from .views.word_of_knowledge import (
    WordOfKnowledgeListView, WordOfKnowledgeCreateView, HealingCreateView,
    ServiceWordsView, MarkWordAsHealedView
)
from .views.ministration_admin import (
    MinistrationWordsListView, MinistrationHealingsListView, MinistrationMembersListView,
    MinistrationAddMemberView, MinistrationRemoveMemberView, MinistrationToggleApproverView
)
from .views.ministry import (
    MinistryListView, MinistryCreateView, MinistryUpdateView, MinistryDeleteView,
    MinistryMembersView, MinistryAddMembersPageView, MinistryAddMemberView,
    MinistryRemoveMemberView, MinistryToggleRoleView, MinistryToggleStatusView
)
from .views.ministration_dashboard import MinistrationDashboardView
from .views.course_attendance import (
    AttendanceCourseListView,
    AttendanceCourseEditView,
    AttendanceCourseDashboardView,
    AttendanceCourseAttendanceListView,
    CourseParticipantListView,
    CourseParticipantCreateView,
    CourseParticipantDetailView,
    CourseParticipantDeleteView,
    CourseLessonListView,
    CourseLessonCreateView,
    CourseLessonDetailView,
    CourseLessonAttendanceView,
    AttendanceCourseReportExportView,
    AttendanceCourseReportPrintView,
    AttendanceLessonReportPrintView,
)
from .views.word_approval import PendingWordsListView, ApproveWordView, RejectWordView
from .views.schedules import (
    TeamListView, TeamCreateView, TeamEditView, TeamDeleteView,
    ScheduleListView, ScheduleCreateView, ScheduleEditView, ScheduleDetailView,
    ScheduleDeleteView,
    ScheduleDayCreateView, ScheduleDayEditView, ScheduleDayDeleteView,
    ScheduleDayGetView, ScheduleDayToggleCancelView,
    schedule_print_view,
    check_schedule_conflict_view,
    DivisionListView, DivisionCreateView, DivisionEditView, DivisionDeleteView,
    ScheduleDayDivisionAssignView
)
from .views.prayer_request import PrayerRequestCreateView, PrayerRequestListView
from .views.house_of_peace import (
    HouseOfPeacePublicCreateView,
    HouseOfPeacePublicSuccessView,
    HouseOfPeaceAvailableListView,
    HouseOfPeaceAcceptView,
    HouseOfPeaceMyListView,
    HouseOfPeaceScheduleView,
    HouseOfPeaceCompleteView,
    HouseOfPeaceDetailView,
    HouseOfPeaceRescheduleView,
    HouseOfPeaceCancelScheduleView,
)
from .views.admin_panel import (
    DashboardView, MembersListView, VisitorsListView,
    EventsListView, NeighborhoodsListView,
    ApiDeleteItemView, MinistryCreateEditApiView, NeighborhoodCreateEditApiView,
    MemberDetailApiView, VisitorDetailApiView, MemberEditView, VisitorEditView, EventEditView,
    NeighborhoodEditView, FollowUpListView, FollowUpEditView,
    FollowUpDeleteView, FollowUpReportView, FollowUpDetailView,
    CanteenListView, CanteenEditView, CanteenDetailView, CanteenDeleteView,
    CanteenTogglePaidView, CanteenApiView, TemplatesListView, ReportsView,
    TemplateCreateView, TemplateEditView, TemplateDetailView, TemplateDeleteView,
    TestimonyListView as AdminTestimonyListView, TestimonyEditView, TestimonyDeleteView, TestimonyToggleView,
    RoteiroView, AnuncioCreateView, AnuncioEditView, AnuncioDeleteView,
    AnuncioReorderView, RoteiroPrintView,
    AdminHouseOfPeaceListView, AdminHouseOfPeaceDetailView,
    AdminHouseOfPeaceStatusView, AdminHouseOfPeaceDeleteView,
    AdminExternalMediaTemplateDeleteView,
    AdminExternalMediaTemplateDetailView,
    AdminExternalMediaTemplateEditView, AdminExternalMediaTemplateListView,
    AdminExternalMediaVersionDuplicateView, AdminExternalMediaVersionFormView,
    AdminExternalMediaVersionPublishView,
    AdminExternalMediaBackgroundMusicDeleteView, AdminExternalMediaBackgroundMusicSaveView,
    AdminExternalMediaColorLUTDeleteView, AdminExternalMediaColorLUTSaveView,
    AdminExternalMediaOverlayPresetDeleteView, AdminExternalMediaOverlayPresetListView,
    AdminExternalMediaGlossaryDeleteView, AdminExternalMediaGlossaryUpdateView, AdminExternalMediaGlossaryView,
    AdminExternalMediaMasteringProfileDeleteView, AdminExternalMediaMasteringProfileSaveView,
    AdminExternalMediaPresetDeleteView, AdminExternalMediaPresetSaveView,
    AdminExternalMediaSpeechFillerTermDeleteView, AdminExternalMediaSpeechFillerTermSaveView,
    AdminExternalMediaSubtitleStyleDeleteView, AdminExternalMediaSubtitleStyleSaveView,
)
from .views.prosperar import (
    ProsperarCompanyRegisterView,
    ProsperarCompanyRegisterSuccessView,
    ProsperarLoginView,
    ProsperarLogoutView,
    ProsperarDashboardView,
    ProsperarProfileView,
)
from .views.external_media import (
    ExternalMediaAssetDownloadView,
    ExternalMediaCreateView,
    ExternalMediaDashboardView,
    ExternalMediaDetailView,
    ExternalMediaEditorView,
    ExternalMediaGlossaryDeleteView,
    ExternalMediaGlossaryView,
    ExternalMediaOriginalDownloadView,
    ExternalMediaProjectDetailView,
    ExternalMediaProjectEditView,
    ExternalMediaProjectResumeEditingView,
    ExternalMediaProjectReopenReviewView,
    ExternalMediaProjectRestoreProcessedResultView,
    ExternalMediaProjectDeleteView,
    ExternalMediaProjectDuplicateView,
    ExternalMediaProjectExportDownloadView,
    ExternalMediaProjectExportStatusView,
    ExternalMediaProjectMediaDeleteView,
    ExternalMediaProjectMediaPreviewView,
    ExternalMediaProjectMediaStatusView,
    ExternalMediaProjectMediaTrimView,
    ExternalMediaProjectMediaReorderView,
    ExternalMediaProjectCustomBlockMediaReorderView,
    ExternalMediaProjectBrollUploadView,
    ExternalMediaProjectBrollUploadPresignView,
    ExternalMediaProjectBrollUploadCompleteView,
    ExternalMediaProjectBrollDeleteView,
    ExternalMediaProjectBrollPreviewView,
    ExternalMediaProjectBrollStatusView,
    ExternalMediaProjectBrollTrimView,
    ExternalMediaProjectCustomBlockView,
    ExternalMediaProjectCustomBlockDeleteView,
    ExternalMediaProjectCustomBlockUploadView,
    ExternalMediaProjectCustomBlockReorderView,
    ExternalMediaProjectRenderView,
    ExternalMediaProjectPreviewView,
    ExternalMediaProjectPreviewSourceView,
    ExternalMediaProjectPreviewMasterView,
    ExternalMediaProjectPreviewMusicView,
    ExternalMediaProjectPreviewDecisionView,
    ExternalMediaProjectPreviewApplyAllNoiseView,
    ExternalMediaProjectPreviewCutView,
    ExternalMediaProjectPreviewNoiseClipView,
    ExternalMediaProjectPreviewSubtitleView,
    ExternalMediaProjectPreviewTransformView,
    ExternalMediaProjectPreviewOverlayView,
    ExternalMediaProjectPreviewOverlayAssetView,
    ExternalMediaProjectPreviewBrollView,
    ExternalMediaProjectPreviewBrollAssetView,
    ExternalMediaProjectPreviewBrollUploadView,
    ExternalMediaProjectOverlayDataView,
    ExternalMediaProjectPreviewSessionView,
    ExternalMediaProjectPreviewHistoryView,
    ExternalMediaProjectPreviewRedoView,
    ExternalMediaProjectPreviewApproveView,
    ExternalMediaProjectRunView,
    ExternalMediaProjectPremiereExportView,
    ExternalMediaProjectSettingsView,
    ExternalMediaProjectStatusView,
    ExternalMediaProjectUploadView,
    ExternalMediaProjectUploadPresignView,
    ExternalMediaProjectCustomBlockUploadPresignView,
    ExternalMediaProjectUploadCompleteView,
    ExternalMediaProjectTimelineDownloadView,
    ExternalMediaRenderView,
    ExternalMediaRetryView,
    ExternalMediaStatusView,
    VideoMasteringCreateView,
    VideoMasteringDetailView,
    VideoMasteringOriginalView,
    VideoMasteringOutputView,
    VideoMasteringRunView,
    VideoMasteringStatusView,
)
from .views.subtitle_review import (
    ProjectSubtitleReviewApproveAllView,
    ProjectSubtitleReviewDetailView,
    ProjectSubtitleReviewRenderView,
    ProjectSubtitleReviewRevokeView,
    ProjectSubtitleReviewsView,
    ProjectSubtitleSuggestionDecisionView,
    ProjectSubtitleVideoVersionAssetView,
    PublicSubtitleReviewAutosaveView,
    PublicSubtitleReviewPreviewView,
    PublicSubtitleReviewSubmitView,
    PublicSubtitleReviewView,
)

urlpatterns = [
    path('ministries/', ministry_org.MinistryOrganizationIndex.as_view(), name='ministry_organization_index'),
    path('ministries/<int:ministry_id>/teams/', ministry_org.MinistryTeamList.as_view(), name='ministry_team_list'),
    path('ministries/<int:ministry_id>/teams/new/', ministry_org.MinistryTeamEdit.as_view(), name='ministry_team_create'),
    path('ministries/<int:ministry_id>/teams/<int:pk>/', ministry_org.MinistryTeamDetail.as_view(), name='ministry_team_detail'),
    path('ministries/<int:ministry_id>/teams/<int:pk>/edit/', ministry_org.MinistryTeamEdit.as_view(), name='ministry_team_edit'),
    path('ministries/<int:ministry_id>/teams/<int:pk>/members/add/', ministry_org.MinistryTeamMemberEdit.as_view(), name='ministry_team_member_add'),
    path('ministries/<int:ministry_id>/teams/<int:pk>/members/<int:membership_id>/edit/', ministry_org.MinistryTeamMemberEdit.as_view(), name='ministry_team_member_edit'),
    path('ministries/<int:ministry_id>/teams/<int:pk>/members/<int:membership_id>/remove/', ministry_org.MinistryTeamMemberRemove.as_view(), name='ministry_team_member_remove'),
    path('ministries/<int:ministry_id>/manuals/', ministry_org.MinistryManualList.as_view(), name='ministry_manual_list'),
    path('ministries/<int:ministry_id>/manuals/preview/', ministry_org.MinistryManualPreview.as_view(), name='ministry_manual_preview'),
    path('ministries/<int:ministry_id>/manuals/new/', ministry_org.MinistryManualEdit.as_view(), name='ministry_manual_create'),
    path('ministries/<int:ministry_id>/manuals/<int:pk>/', ministry_org.MinistryManualDetail.as_view(), name='ministry_manual_detail'),
    path('ministries/<int:ministry_id>/manuals/<int:pk>/edit/', ministry_org.MinistryManualEdit.as_view(), name='ministry_manual_edit'),
    path('ministries/<int:ministry_id>/manuals/<int:pk>/archive/', ministry_org.MinistryManualArchive.as_view(), name='ministry_manual_archive'),

    path('', HomeView.as_view(), name='home'),
    path('testemunhos/', TestimonyListView.as_view(), name='testemunhos'),
    path('contato/', ContactView.as_view(), name='contato'),
    path('visitor/', VisitorCreateView.as_view(), name='visitor'),
    path('prayer-request/', PrayerRequestCreateView.as_view(), name='prayer_request_create'),
    path('prayer-request/list', PrayerRequestListView.as_view(), name='prayer_request_list'),
    path('evangelism/', EvangelismCreateView.as_view(), name='evangelism'),

    # House of Peace — public form (no login)
    path('house-of-peace/', HouseOfPeacePublicCreateView.as_view(), name='house_of_peace_public_form'),
    path('house-of-peace/sucesso/', HouseOfPeacePublicSuccessView.as_view(), name='house_of_peace_public_success'),
    path('prosperar/register/', ProsperarCompanyRegisterView.as_view(), name='prosperar_company_register'),
    path('prosperar/register/success/', ProsperarCompanyRegisterSuccessView.as_view(), name='prosperar_register_success'),
    path('prosperar/login/', ProsperarLoginView.as_view(), name='prosperar_login'),
    path('review/subtitles/<str:token>/', PublicSubtitleReviewView.as_view(), name='public_subtitle_review'),
    path('review/subtitles/<str:token>/autosave/', PublicSubtitleReviewAutosaveView.as_view(), name='public_subtitle_review_autosave'),
    path('review/subtitles/<str:token>/submit/', PublicSubtitleReviewSubmitView.as_view(), name='public_subtitle_review_submit'),
    path('review/subtitles/<str:token>/preview/', PublicSubtitleReviewPreviewView.as_view(), name='public_subtitle_review_preview'),

    # House of Peace — member area
    path('house-of-peace/available/', HouseOfPeaceAvailableListView.as_view(), name='house_of_peace_available'),
    path('house-of-peace/<int:house_id>/accept/', HouseOfPeaceAcceptView.as_view(), name='house_of_peace_accept'),
    path('house-of-peace/my/', HouseOfPeaceMyListView.as_view(), name='house_of_peace_my_list'),
    path('house-of-peace/assignment/<int:assignment_id>/schedule/', HouseOfPeaceScheduleView.as_view(), name='house_of_peace_schedule'),
    path('house-of-peace/assignment/<int:assignment_id>/reschedule/', HouseOfPeaceRescheduleView.as_view(), name='house_of_peace_reschedule'),
    path('house-of-peace/assignment/<int:assignment_id>/cancel-schedule/', HouseOfPeaceCancelScheduleView.as_view(), name='house_of_peace_cancel_schedule'),
    path('house-of-peace/assignment/<int:assignment_id>/complete/', HouseOfPeaceCompleteView.as_view(), name='house_of_peace_complete'),
    path('house-of-peace/<int:house_id>/details/', HouseOfPeaceDetailView.as_view(), name='house_of_peace_detail'),

    path('evangelism/list/', EvangelismListView.as_view(), name='evangelism_list'),
    path('new_converts/list/', NewConvertsListView.as_view(), name='new_converts_list'),
    path('member/register/', MemberCreateView.as_view(), name='member_register'),
    path('translator/recorder/', AudioRecorderView.as_view(), name='audio_recorder'),
    path('translator/', TranscriptionDisplayView.as_view(), name='transcription'),
    path('event/list', EventListView.as_view(), name='event_list'),
    path('event/<slug:slug>/', EventDetailView.as_view(), name='event_detail'),
    
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset/request.html',
        email_template_name='password_reset/email.html',
        html_email_template_name='password_reset/email_html.html',
        subject_template_name='password_reset/email_subject.txt',
        success_url='/password-reset/sent/',
        extra_email_context={'site_domain': settings.SITE_DOMAIN},
    ), name='password_reset_request'),
    path('password-reset/sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset/email_sent.html',
    ), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset/confirm.html',
        success_url='/password-reset/complete/',
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/complete.html',
    ), name='password_reset_complete'),

    path('login/', MemberLoginView.as_view(), name='member_login'),
    path('admin-login/', MemberLoginView.as_view(), name='admin_login'),  # Redirect old admin login to unified login
    path('redirect-after-login/', RedirectAfterLoginView.as_view(), name='redirect_after_login'),
    path('dashboard/', MemberDashboardView.as_view(), name='member_dashboard'),
    path('member/media/', ExternalMediaDashboardView.as_view(), name='external_media_dashboard'),
    path('member/media/new/', ExternalMediaCreateView.as_view(), name='external_media_create'),
    path('member/media/projects/<uuid:public_id>/', ExternalMediaProjectDetailView.as_view(), name='external_media_project_detail'),
    path('member/media/projects/<uuid:public_id>/edit/', ExternalMediaProjectEditView.as_view(), name='external_media_project_edit'),
    path('member/media/projects/<uuid:public_id>/resume-editing/', ExternalMediaProjectResumeEditingView.as_view(), name='external_media_project_resume_editing'),
    path('member/media/projects/<uuid:public_id>/reopen-review/', ExternalMediaProjectReopenReviewView.as_view(), name='external_media_project_reopen_review'),
    path('member/media/projects/<uuid:public_id>/restore-processed-result/', ExternalMediaProjectRestoreProcessedResultView.as_view(), name='external_media_project_restore_processed_result'),
    path('member/media/projects/<uuid:public_id>/delete/', ExternalMediaProjectDeleteView.as_view(), name='external_media_project_delete'),
    path('member/media/projects/<uuid:public_id>/status/', ExternalMediaProjectStatusView.as_view(), name='external_media_project_status'),
    path('member/media/projects/<uuid:public_id>/run/', ExternalMediaProjectRunView.as_view(), name='external_media_project_run'),
    path('member/media/projects/<uuid:public_id>/settings/', ExternalMediaProjectSettingsView.as_view(), name='external_media_project_settings'),
    path('member/media/projects/<uuid:public_id>/render/', ExternalMediaProjectRenderView.as_view(), name='external_media_project_render'),
    path('member/media/projects/<uuid:public_id>/preview/', ExternalMediaProjectPreviewView.as_view(), name='external_media_project_preview'),
    path('member/media/projects/<uuid:public_id>/preview/sources/<path:source_id>/', ExternalMediaProjectPreviewSourceView.as_view(), name='external_media_project_preview_source'),
    path('member/media/projects/<uuid:public_id>/preview/master/', ExternalMediaProjectPreviewMasterView.as_view(), name='external_media_project_preview_master'),
    path('member/media/projects/<uuid:public_id>/preview/music/', ExternalMediaProjectPreviewMusicView.as_view(), name='external_media_project_preview_music'),
    path('member/media/projects/<uuid:public_id>/preview/decisions/<str:decision_id>/', ExternalMediaProjectPreviewDecisionView.as_view(), name='external_media_project_preview_decision'),
    path('member/media/projects/<uuid:public_id>/preview/noise/apply-all/', ExternalMediaProjectPreviewApplyAllNoiseView.as_view(), name='external_media_project_preview_noise_apply_all'),
    path('member/media/projects/<uuid:public_id>/preview/cuts/', ExternalMediaProjectPreviewCutView.as_view(), name='external_media_project_preview_cut_create'),
    path('member/media/projects/<uuid:public_id>/preview/noise/<str:decision_id>/', ExternalMediaProjectPreviewNoiseClipView.as_view(), name='external_media_project_preview_noise_clip'),
    path('member/media/projects/<uuid:public_id>/preview/subtitles/<int:cue_id>/', ExternalMediaProjectPreviewSubtitleView.as_view(), name='external_media_project_preview_subtitle'),
    path('member/media/projects/<uuid:public_id>/preview/transforms/<str:decision_id>/', ExternalMediaProjectPreviewTransformView.as_view(), name='external_media_project_preview_transform'),
    path('member/media/projects/<uuid:public_id>/preview/overlays/new/', ExternalMediaProjectPreviewOverlayView.as_view(), name='external_media_project_preview_overlay_create'),
    path('member/media/projects/<uuid:public_id>/preview/overlays/<str:overlay_id>/', ExternalMediaProjectPreviewOverlayView.as_view(), name='external_media_project_preview_overlay'),
    path('member/media/projects/<uuid:public_id>/preview/overlays/<str:overlay_id>/asset.png', ExternalMediaProjectPreviewOverlayAssetView.as_view(), name='external_media_project_preview_overlay_asset'),
    path('member/media/projects/<uuid:public_id>/preview/brolls/new/', ExternalMediaProjectPreviewBrollUploadView.as_view(), name='external_media_project_preview_broll_create'),
    path('member/media/projects/<uuid:public_id>/preview/brolls/<str:broll_id>/', ExternalMediaProjectPreviewBrollView.as_view(), name='external_media_project_preview_broll'),
    path('member/media/projects/<uuid:public_id>/preview/broll-assets/<uuid:asset_id>/', ExternalMediaProjectPreviewBrollAssetView.as_view(), name='external_media_project_preview_broll_asset'),
    path('member/media/projects/<uuid:public_id>/preview/session/', ExternalMediaProjectPreviewSessionView.as_view(), name='external_media_project_preview_session'),
    path('member/media/projects/<uuid:public_id>/preview/undo/', ExternalMediaProjectPreviewHistoryView.as_view(), name='external_media_project_preview_undo'),
    path('member/media/projects/<uuid:public_id>/preview/redo/', ExternalMediaProjectPreviewRedoView.as_view(), name='external_media_project_preview_redo'),
    path('member/media/projects/<uuid:public_id>/preview/approve/', ExternalMediaProjectPreviewApproveView.as_view(), name='external_media_project_preview_approve'),
    path('member/media/projects/<uuid:public_id>/subtitles/reviews/', ProjectSubtitleReviewsView.as_view(), name='external_media_project_subtitle_reviews'),
    path('member/media/projects/<uuid:public_id>/subtitles/apply/', ProjectSubtitleReviewRenderView.as_view(), name='external_media_project_subtitle_render'),
    path('member/media/projects/<uuid:public_id>/subtitles/versions/assets/<int:asset_id>/', ProjectSubtitleVideoVersionAssetView.as_view(), name='external_media_project_subtitle_version_asset'),
    path('member/media/projects/<uuid:public_id>/subtitles/reviews/<int:session_id>/', ProjectSubtitleReviewDetailView.as_view(), name='external_media_project_subtitle_review_detail'),
    path('member/media/projects/<uuid:public_id>/subtitles/reviews/<int:session_id>/revoke/', ProjectSubtitleReviewRevokeView.as_view(), name='external_media_project_subtitle_review_revoke'),
    path('member/media/projects/<uuid:public_id>/subtitles/reviews/<int:session_id>/approve-all/', ProjectSubtitleReviewApproveAllView.as_view(), name='external_media_project_subtitle_review_approve_all'),
    path('member/media/projects/<uuid:public_id>/subtitles/reviews/<int:session_id>/apply/', ProjectSubtitleReviewRenderView.as_view(), name='external_media_project_subtitle_review_render'),
    path('member/media/projects/<uuid:public_id>/subtitles/reviews/<int:session_id>/suggestions/<int:suggestion_id>/', ProjectSubtitleSuggestionDecisionView.as_view(), name='external_media_project_subtitle_suggestion_decide'),
    path('member/media/projects/<uuid:public_id>/duplicate/', ExternalMediaProjectDuplicateView.as_view(), name='external_media_project_duplicate'),
    path('member/media/projects/<uuid:public_id>/exports/premiere/', ExternalMediaProjectPremiereExportView.as_view(), name='external_media_project_export_premiere'),
    path('member/media/projects/<uuid:public_id>/exports/<uuid:export_public_id>/status/', ExternalMediaProjectExportStatusView.as_view(), name='external_media_project_export_status'),
    path('member/media/projects/<uuid:public_id>/exports/<uuid:export_public_id>/download/', ExternalMediaProjectExportDownloadView.as_view(), name='external_media_project_export_download'),
    path('member/media/projects/<uuid:public_id>/exports/<uuid:export_public_id>/timeline/', ExternalMediaProjectTimelineDownloadView.as_view(), name='external_media_project_export_timeline'),
    path('member/media/projects/<uuid:public_id>/blocks/<int:block_id>/upload/', ExternalMediaProjectUploadView.as_view(), name='external_media_project_upload'),
    path('member/media/projects/<uuid:public_id>/blocks/<int:block_id>/brolls/', ExternalMediaProjectBrollUploadView.as_view(), name='external_media_project_broll_upload'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/<int:block_id>/brolls/', ExternalMediaProjectBrollUploadView.as_view(), {'custom': True}, name='external_media_project_custom_broll_upload'),
    path('member/media/projects/<uuid:public_id>/blocks/<int:block_id>/brolls/presign/', ExternalMediaProjectBrollUploadPresignView.as_view(), name='external_media_project_broll_upload_presign'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/<int:block_id>/brolls/presign/', ExternalMediaProjectBrollUploadPresignView.as_view(), {'custom': True}, name='external_media_project_custom_broll_upload_presign'),
    path('member/media/projects/<uuid:public_id>/brolls/uploads/complete/', ExternalMediaProjectBrollUploadCompleteView.as_view(), name='external_media_project_broll_upload_complete'),
    path('member/media/projects/<uuid:public_id>/brolls/<uuid:asset_id>/delete/', ExternalMediaProjectBrollDeleteView.as_view(), name='external_media_project_broll_delete'),
    path('member/media/projects/<uuid:public_id>/brolls/<uuid:asset_id>/preview/', ExternalMediaProjectBrollPreviewView.as_view(), name='external_media_project_broll_preview'),
    path('member/media/projects/<uuid:public_id>/brolls/<uuid:asset_id>/status/', ExternalMediaProjectBrollStatusView.as_view(), name='external_media_project_broll_status'),
    path('member/media/projects/<uuid:public_id>/brolls/<uuid:asset_id>/trim/', ExternalMediaProjectBrollTrimView.as_view(), name='external_media_project_broll_trim'),
    path('member/media/projects/<uuid:public_id>/blocks/<int:block_id>/presign/', ExternalMediaProjectUploadPresignView.as_view(), name='external_media_project_upload_presign'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/<int:block_id>/presign/', ExternalMediaProjectCustomBlockUploadPresignView.as_view(), name='external_media_project_custom_block_upload_presign'),
    path('member/media/projects/<uuid:public_id>/uploads/complete/', ExternalMediaProjectUploadCompleteView.as_view(), name='external_media_project_upload_complete'),
    path('member/media/projects/<uuid:public_id>/overlays/<str:overlay_id>/data/', ExternalMediaProjectOverlayDataView.as_view(), name='external_media_project_overlay_data'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/new/', ExternalMediaProjectCustomBlockView.as_view(), name='external_media_project_custom_block_create'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/<int:block_id>/edit/', ExternalMediaProjectCustomBlockView.as_view(), name='external_media_project_custom_block_edit'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/<int:block_id>/delete/', ExternalMediaProjectCustomBlockDeleteView.as_view(), name='external_media_project_custom_block_delete'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/reorder/', ExternalMediaProjectCustomBlockReorderView.as_view(), name='external_media_project_custom_block_reorder'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/<int:block_id>/upload/', ExternalMediaProjectCustomBlockUploadView.as_view(), name='external_media_project_custom_block_upload'),
    path('member/media/projects/<uuid:public_id>/custom-blocks/<int:block_id>/reorder-media/', ExternalMediaProjectCustomBlockMediaReorderView.as_view(), name='external_media_project_custom_block_media_reorder'),
    path('member/media/projects/<uuid:public_id>/blocks/<int:block_id>/reorder/', ExternalMediaProjectMediaReorderView.as_view(), name='external_media_project_media_reorder'),
    path('member/media/projects/<uuid:public_id>/uploads/<int:media_id>/delete/', ExternalMediaProjectMediaDeleteView.as_view(), name='external_media_project_media_delete'),
    path('member/media/projects/<uuid:public_id>/uploads/<int:media_id>/preview/', ExternalMediaProjectMediaPreviewView.as_view(), name='external_media_project_media_preview'),
    path('member/media/projects/<uuid:public_id>/uploads/<int:media_id>/status/', ExternalMediaProjectMediaStatusView.as_view(), name='external_media_project_media_status'),
    path('member/media/projects/<uuid:public_id>/uploads/<int:media_id>/trim/', ExternalMediaProjectMediaTrimView.as_view(), name='external_media_project_media_trim'),
    path('member/media/glossary/', ExternalMediaGlossaryView.as_view(), name='external_media_glossary'),
    path('member/media/glossary/<int:term_id>/delete/', ExternalMediaGlossaryDeleteView.as_view(), name='external_media_glossary_delete'),
    path('member/media/mastering/new/', VideoMasteringCreateView.as_view(), name='external_media_mastering_create'),
    path('member/media/mastering/<uuid:public_id>/', VideoMasteringDetailView.as_view(), name='external_media_mastering_detail'),
    path('member/media/mastering/<uuid:public_id>/run/', VideoMasteringRunView.as_view(), name='external_media_mastering_run'),
    path('member/media/mastering/<uuid:public_id>/status/', VideoMasteringStatusView.as_view(), name='external_media_mastering_status'),
    path('member/media/mastering/<uuid:public_id>/original/', VideoMasteringOriginalView.as_view(), name='external_media_mastering_original'),
    path('member/media/mastering/<uuid:public_id>/output/', VideoMasteringOutputView.as_view(), name='external_media_mastering_output'),
    path('member/media/<uuid:public_id>/', ExternalMediaDetailView.as_view(), name='external_media_detail'),
    path('member/media/<uuid:public_id>/status/', ExternalMediaStatusView.as_view(), name='external_media_status'),
    path('member/media/<uuid:public_id>/editor/', ExternalMediaEditorView.as_view(), name='external_media_editor'),
    path('member/media/<uuid:public_id>/retry/', ExternalMediaRetryView.as_view(), name='external_media_retry'),
    path('member/media/<uuid:public_id>/render/', ExternalMediaRenderView.as_view(), name='external_media_render'),
    path('member/media/<uuid:public_id>/original/', ExternalMediaOriginalDownloadView.as_view(), name='external_media_original'),
    path('member/media/<uuid:public_id>/assets/<int:asset_id>/', ExternalMediaAssetDownloadView.as_view(), name='external_media_asset'),
    path('prosperar/dashboard/', ProsperarDashboardView.as_view(), name='prosperar_dashboard'),
    path('prosperar/profile/', ProsperarProfileView.as_view(), name='prosperar_profile'),
    path('logout/', MemberLogoutView.as_view(), name='member_logout'),
    path('prosperar/logout/', ProsperarLogoutView.as_view(), name='prosperar_logout'),
    path('admin-logout/', MemberLogoutView.as_view(), name='admin_logout'),
    path('profile/', MemberProfileView.as_view(), name='member_profile'),
    path('roteiro-culto/', MemberRoteiroView.as_view(), name='member_roteiro'),
    
    # Member Word Approval URLs
    path('words/approve/<int:word_id>/', MemberApproveWordView.as_view(), name='member_approve_word'),
    path('words/reject/<int:word_id>/', MemberRejectWordView.as_view(), name='member_reject_word'),
    
    # Member Consolidation URLs
    path('consolidation/', MemberConsolidationListView.as_view(), name='member_consolidation'),
    path('consolidation/<int:followup_id>/', MemberConsolidationDetailView.as_view(), name='member_consolidation_detail'),
    path('consolidation/<int:followup_id>/report/', MemberConsolidationReportView.as_view(), name='member_consolidation_report'),
    path('consolidation/guide/', ConsolidatorGuideView.as_view(), name='consolidator_guide'),
    path('consolidation/assignments/', ConsolidatorAssignmentsView.as_view(), name='consolidator_assignments'),
    path('consolidation/request/<int:person_id>/', RequestConsolidationView.as_view(), name='request_consolidation'),

    # Boas Vindas - member visitor registration & list
    path('register-visitor/', MemberVisitorCreateView.as_view(), name='member_visitor_create'),
    path('visitors/', MemberVisitorListView.as_view(), name='member_visitor_list'),
    path('pastoral/visitors/', PastoralVisitorListView.as_view(), name='pastoral_visitor_list'),
    path('pastoral/visitors/report/', PastoralVisitorReportView.as_view(), name='pastoral_visitor_report'),

    # Member Schedules
    path('schedule/<int:schedule_id>/', MemberScheduleDetailView.as_view(), name='member_schedule_detail'),
    
    # Words of Knowledge URLs
    path('words/', WordOfKnowledgeListView.as_view(), name='word_of_knowledge_list'),
    path('words/create/', WordOfKnowledgeCreateView.as_view(), name='word_of_knowledge_create'),
    path('words/healing/create/', HealingCreateView.as_view(), name='healing_create'),
    path('words/service/', ServiceWordsView.as_view(), name='service_words_view'),
    path('words/<int:word_id>/mark-healed/', MarkWordAsHealedView.as_view(), name='mark_word_as_healed'),
    
    # Ministration URLs
    path('admin-panel/ministration/', MinistrationDashboardView.as_view(), name='ministration_dashboard'),
    path('admin-panel/ministration/words/', MinistrationWordsListView.as_view(), name='ministration_words_list'),
    path('admin-panel/ministration/words/pending/', PendingWordsListView.as_view(), name='pending_words_list'),
    path('admin-panel/ministration/words/approve/<int:word_id>/', ApproveWordView.as_view(), name='approve_word'),
    path('admin-panel/ministration/words/reject/<int:word_id>/', RejectWordView.as_view(), name='reject_word'),
    path('admin-panel/ministration/healings/', MinistrationHealingsListView.as_view(), name='ministration_healings_list'),
    path('admin-panel/ministration/members/', MinistrationMembersListView.as_view(), name='ministration_members_list'),
    path('admin-panel/ministration/members/<int:member_id>/add/', MinistrationAddMemberView.as_view(), name='ministration_add_member'),
    path('admin-panel/ministration/members/<int:member_id>/remove/', MinistrationRemoveMemberView.as_view(), name='ministration_remove_member'),
    path('admin-panel/ministration/members/<int:member_id>/toggle-approver/', MinistrationToggleApproverView.as_view(), name='ministration_toggle_approver'),
    
    # Schedule URLs - Sistema de Escalas
    path('admin-panel/schedules/', ScheduleListView.as_view(), name='schedule_list'),
    path('admin-panel/schedules/new/', ScheduleCreateView.as_view(), name='schedule_create'),
    path('admin-panel/schedules/<int:schedule_id>/', ScheduleDetailView.as_view(), name='schedule_detail'),
    path('admin-panel/schedules/<int:schedule_id>/edit/', ScheduleEditView.as_view(), name='schedule_edit'),
    path('admin-panel/schedules/<int:schedule_id>/delete/', ScheduleDeleteView.as_view(), name='schedule_delete'),
    # publish/unpublish removed — schedule for current month is always active
    path('admin-panel/schedules/<int:schedule_id>/print/', schedule_print_view, name='schedule_print'),
    
    # Schedule Days URLs
    path('admin-panel/schedules/<int:schedule_id>/days/new/', ScheduleDayCreateView.as_view(), name='schedule_day_create'),
    path('admin-panel/schedules/days/<int:day_id>/get/', ScheduleDayGetView.as_view(), name='schedule_day_get'),
    path('admin-panel/schedules/days/<int:day_id>/edit/', ScheduleDayEditView.as_view(), name='schedule_day_edit'),
    path('admin-panel/schedules/days/<int:day_id>/delete/', ScheduleDayDeleteView.as_view(), name='schedule_day_delete'),
    path('admin-panel/schedules/days/<int:day_id>/toggle-cancel/', ScheduleDayToggleCancelView.as_view(), name='schedule_day_toggle_cancel'),
    path('admin-panel/schedules/check-conflict/', check_schedule_conflict_view, name='schedule_check_conflict'),
    
    # Division URLs - Subdivisões de Escala (gerenciadas inline no form da escala)
    path('admin-panel/ministries/<int:ministry_id>/divisions/', DivisionListView.as_view(), name='division_list'),
    path('admin-panel/schedules/<int:schedule_id>/divisions/new/', DivisionCreateView.as_view(), name='division_create'),
    path('admin-panel/divisions/<int:division_id>/edit/', DivisionEditView.as_view(), name='division_edit'),
    path('admin-panel/divisions/<int:division_id>/delete/', DivisionDeleteView.as_view(), name='division_delete'),
    path('admin-panel/schedules/days/<int:day_id>/divisions/', ScheduleDayDivisionAssignView.as_view(), name='schedule_day_division_assign'),
    
    # Team URLs
    path('admin-panel/teams/', TeamListView.as_view(), name='team_list'),
    path('admin-panel/teams/new/', TeamCreateView.as_view(), name='team_create'),
    path('admin-panel/teams/<int:team_id>/edit/', TeamEditView.as_view(), name='team_edit'),
    path('admin-panel/teams/<int:team_id>/delete/', TeamDeleteView.as_view(), name='team_delete'),
    
    # Admin Panel URLs
    path('admin-panel/', DashboardView.as_view(), name='admin_dashboard'),
    path('admin-panel/members/', MembersListView.as_view(), name='admin_members_list'),
    path('admin-panel/members/new/', MemberEditView.as_view(), name='admin_member_create'),
    path('admin-panel/members/<int:member_id>/edit/', MemberEditView.as_view(), name='admin_member_edit'),
    path('admin-panel/visitors/', VisitorsListView.as_view(), name='admin_visitors_list'),
    path('admin-panel/visitors/new/', VisitorEditView.as_view(), name='admin_visitor_create'),
    path('admin-panel/visitors/<int:visitor_id>/edit/', VisitorEditView.as_view(), name='admin_visitor_edit'),
    path('admin-panel/events/', EventsListView.as_view(), name='admin_events_list'),
    path('admin-panel/events/new/', EventEditView.as_view(), name='admin_event_create'),
    path('admin-panel/events/<int:event_id>/edit/', EventEditView.as_view(), name='admin_event_edit'),
    path('admin-panel/music/', MusicListView.as_view(), name='admin_music_list'),
    path('admin-panel/music/new/', MusicCreateView.as_view(), name='admin_music_create'),
    path('admin-panel/music/edit/<int:pk>/', MusicUpdateView.as_view(), name='admin_music_edit'),
    path('admin-panel/music/delete/<int:pk>/', MusicDeleteView.as_view(), name='admin_music_delete'),
    path('ministerio-louvor/', MusicUserListView.as_view(), name='music_user_list'),
    path('admin-panel/neighborhoods/', NeighborhoodsListView.as_view(), name='admin_neighborhoods_list'),
    path('admin-panel/neighborhoods/new/', NeighborhoodEditView.as_view(), name='admin_neighborhood_create'),
    path('admin-panel/neighborhoods/<int:neighborhood_id>/edit/', NeighborhoodEditView.as_view(), name='admin_neighborhood_edit'),
    path('admin-panel/media-templates/', AdminExternalMediaTemplateListView.as_view(), name='admin_external_media_templates'),
    path('admin-panel/media-overlay-presets/', AdminExternalMediaOverlayPresetListView.as_view(), name='admin_external_media_overlay_presets'),
    path('admin-panel/media-overlay-presets/<int:preset_id>/', AdminExternalMediaOverlayPresetListView.as_view(), name='admin_external_media_overlay_preset_edit'),
    path('admin-panel/media-overlay-presets/<int:preset_id>/delete/', AdminExternalMediaOverlayPresetDeleteView.as_view(), name='admin_external_media_overlay_preset_delete'),
    path('admin-panel/media-glossary/', AdminExternalMediaGlossaryView.as_view(), name='admin_external_media_glossary'),
    path('admin-panel/media-glossary/<int:term_id>/edit/', AdminExternalMediaGlossaryUpdateView.as_view(), name='admin_external_media_glossary_edit'),
    path('admin-panel/media-glossary/<int:term_id>/delete/', AdminExternalMediaGlossaryDeleteView.as_view(), name='admin_external_media_glossary_delete'),
    path('admin-panel/media-templates/new/', AdminExternalMediaVersionFormView.as_view(), name='admin_external_media_template_create'),
    path('admin-panel/media-templates/<int:template_id>/', AdminExternalMediaTemplateDetailView.as_view(), name='admin_external_media_template_detail'),
    path('admin-panel/media-templates/<int:template_id>/edit/', AdminExternalMediaTemplateEditView.as_view(), name='admin_external_media_template_edit'),
    path('admin-panel/media-templates/<int:template_id>/delete/', AdminExternalMediaTemplateDeleteView.as_view(), name='admin_external_media_template_delete'),
    path('admin-panel/media-templates/<int:template_id>/versions/new/', AdminExternalMediaVersionFormView.as_view(), name='admin_external_media_version_create'),
    path('admin-panel/media-template-versions/<int:version_id>/edit/', AdminExternalMediaVersionFormView.as_view(), name='admin_external_media_version_edit'),
    path('admin-panel/media-template-versions/<int:version_id>/publish/', AdminExternalMediaVersionPublishView.as_view(), name='admin_external_media_version_publish'),
    path('admin-panel/media-template-versions/<int:version_id>/duplicate/', AdminExternalMediaVersionDuplicateView.as_view(), name='admin_external_media_version_duplicate'),
    path('admin-panel/media-background-music/save/', AdminExternalMediaBackgroundMusicSaveView.as_view(), name='admin_external_media_background_music_save'),
    path('admin-panel/media-background-music/<int:music_id>/delete/', AdminExternalMediaBackgroundMusicDeleteView.as_view(), name='admin_external_media_background_music_delete'),
    path('admin-panel/media-color-luts/save/', AdminExternalMediaColorLUTSaveView.as_view(), name='admin_external_media_color_lut_save'),
    path('admin-panel/media-color-luts/<int:lut_id>/delete/', AdminExternalMediaColorLUTDeleteView.as_view(), name='admin_external_media_color_lut_delete'),
    path('admin-panel/media-mastering-profiles/save/', AdminExternalMediaMasteringProfileSaveView.as_view(), name='admin_external_media_mastering_profile_save'),
    path('admin-panel/media-mastering-profiles/<int:profile_id>/delete/', AdminExternalMediaMasteringProfileDeleteView.as_view(), name='admin_external_media_mastering_profile_delete'),
    path('admin-panel/media-presets/save/', AdminExternalMediaPresetSaveView.as_view(), name='admin_external_media_preset_save'),
    path('admin-panel/media-presets/<int:preset_id>/delete/', AdminExternalMediaPresetDeleteView.as_view(), name='admin_external_media_preset_delete'),
    path('admin-panel/media-subtitle-styles/save/', AdminExternalMediaSubtitleStyleSaveView.as_view(), name='admin_external_media_subtitle_style_save'),
    path('admin-panel/media-subtitle-styles/<int:style_id>/delete/', AdminExternalMediaSubtitleStyleDeleteView.as_view(), name='admin_external_media_subtitle_style_delete'),
    path('admin-panel/media-speech-fillers/save/', AdminExternalMediaSpeechFillerTermSaveView.as_view(), name='admin_external_media_speech_filler_term_save'),
    path('admin-panel/media-speech-fillers/<int:term_id>/delete/', AdminExternalMediaSpeechFillerTermDeleteView.as_view(), name='admin_external_media_speech_filler_term_delete'),
    # User Management URLs
    path('admin-panel/users/', UserManagementView.as_view(), name='admin_user_management'),
    path('admin-panel/users/<int:user_id>/reset-password/', ResetUserPasswordView.as_view(), name='admin_reset_user_password'),
    path('admin-panel/users/<int:user_id>/delete/', DeleteUserView.as_view(), name='admin_delete_user'),
    path('admin-panel/users/<int:user_id>/edit/', UserEditView.as_view(), name='admin_user_edit'),
    path('admin-panel/change-password/', ChangePasswordView.as_view(), name='admin_change_password'),
    
    # Follow-up URLs
    path('admin-panel/followups/', FollowUpListView.as_view(), name='admin_followups_list'),
    path('admin-panel/followups/new/', FollowUpEditView.as_view(), name='admin_followup_create'),
    path('admin-panel/followups/<int:followup_id>/edit/', FollowUpEditView.as_view(), name='admin_followup_edit'),
    path('admin-panel/followups/<int:followup_id>/detail/', FollowUpDetailView.as_view(), name='admin_followup_detail'),
    path('admin-panel/followups/<int:followup_id>/report/', FollowUpReportView.as_view(), name='admin_followup_report'),
    path('admin-panel/followups/<int:followup_id>/delete/', FollowUpDeleteView.as_view(), name='admin_followup_delete'),
    
    # TODO: Implementar as views abaixo
    # Follow-up Templates URLs
    # path('admin-panel/followup-templates/', followup_template_list_view, name='admin_followup_template_list'),
    # path('admin-panel/followup-templates/new/', followup_template_edit_view, name='admin_followup_template_create'),
    # path('admin-panel/followup-templates/<int:template_id>/edit/', followup_template_edit_view, name='admin_followup_template_edit'),
    # path('admin-panel/followup-templates/<int:template_id>/', followup_template_detail_view, name='admin_followup_template_detail'),
    # path('admin-panel/followup-templates/<int:template_id>/delete/', followup_template_delete_view, name='admin_followup_template_delete'),
    # path('admin-panel/followup-templates/<int:template_id>/duplicate/', followup_template_duplicate_view, name='admin_followup_template_duplicate'),
    
    # Follow-up Steps URLs  
    # path('admin-panel/followups/<int:followup_id>/steps/', followup_steps_manage_view, name='admin_followup_steps_manage'),
    # path('admin-panel/followup-steps/<int:step_id>/update-status/', followup_step_update_status, name='admin_followup_step_update_status'),
    # path('admin-panel/followup-steps/<int:step_id>/update-notes/', followup_step_update_notes, name='admin_followup_step_update_notes'),
    # path('admin-panel/followups/<int:followup_id>/complete-all-steps/', followup_complete_all_steps, name='admin_followup_complete_all_steps'),
    # path('admin-panel/followups/<int:followup_id>/generate-steps/', followup_generate_steps, name='admin_followup_generate_steps'),
    
    # Follow-up Reports URLs
    # path('admin-panel/followup-reports/', followup_reports_view, name='admin_followup_reports'),
    
    # Templates e Relatórios URLs
    path('admin-panel/templates/', TemplatesListView.as_view(), name='admin_templates'),
    path('admin-panel/templates/new/', TemplateCreateView.as_view(), name='admin_template_create'),
    path('admin-panel/templates/<int:template_id>/edit/', TemplateEditView.as_view(), name='admin_template_edit'),
    path('admin-panel/templates/<int:template_id>/', TemplateDetailView.as_view(), name='admin_template_detail'),
    path('admin-panel/templates/<int:template_id>/delete/', TemplateDeleteView.as_view(), name='admin_template_delete'),
    path('admin-panel/reports/', ReportsView.as_view(), name='admin_reports'),

    # Listas de Presenca em Cursos
    path('admin-panel/attendance-courses/', AttendanceCourseListView.as_view(), name='attendance_course_list'),
    path('admin-panel/attendance-courses/new/', AttendanceCourseEditView.as_view(), name='attendance_course_create'),
    path('admin-panel/attendance-courses/<int:course_id>/edit/', AttendanceCourseEditView.as_view(), name='attendance_course_edit'),
    path('admin-panel/attendance-courses/<int:course_id>/', AttendanceCourseDashboardView.as_view(), name='attendance_course_dashboard'),
    path('admin-panel/attendance-courses/<int:course_id>/participants/', CourseParticipantListView.as_view(), name='attendance_course_participant_list'),
    path('admin-panel/attendance-courses/<int:course_id>/participants/new/', CourseParticipantCreateView.as_view(), name='attendance_course_participant_create'),
    path('admin-panel/attendance-courses/<int:course_id>/participants/add/', CourseParticipantCreateView.as_view(), name='attendance_course_participant_add'),
    path('admin-panel/attendance-courses/<int:course_id>/participants/<int:participant_id>/', CourseParticipantDetailView.as_view(), name='attendance_course_participant_detail'),
    path('admin-panel/attendance-courses/<int:course_id>/participants/<int:participant_id>/delete/', CourseParticipantDeleteView.as_view(), name='attendance_course_participant_delete'),
    path('admin-panel/attendance-courses/<int:course_id>/lessons/', CourseLessonListView.as_view(), name='attendance_course_lesson_list'),
    path('admin-panel/attendance-courses/<int:course_id>/lessons/new/', CourseLessonCreateView.as_view(), name='attendance_course_lesson_create'),
    path('admin-panel/attendance-courses/<int:course_id>/lessons/add/', CourseLessonCreateView.as_view(), name='attendance_course_lesson_add'),
    path('admin-panel/attendance-courses/<int:course_id>/lessons/<int:lesson_id>/', CourseLessonDetailView.as_view(), name='attendance_course_lesson_detail'),
    path('admin-panel/attendance-courses/<int:course_id>/attendance/', AttendanceCourseAttendanceListView.as_view(), name='attendance_course_attendance_list'),
    path('admin-panel/attendance-courses/lessons/<int:lesson_id>/attendance/', CourseLessonAttendanceView.as_view(), name='attendance_course_lesson_attendance'),
    path('admin-panel/attendance-courses/lessons/<int:lesson_id>/report/print/', AttendanceLessonReportPrintView.as_view(), name='attendance_lesson_report_print'),
    path('admin-panel/attendance-courses/<int:course_id>/report/export/', AttendanceCourseReportExportView.as_view(), name='attendance_course_report_export'),
    path('admin-panel/attendance-courses/<int:course_id>/report/print/', AttendanceCourseReportPrintView.as_view(), name='attendance_course_report_print'),
    
    # Cantina URLs — TODO: templates em admin_panel/cantina/*.html ainda não foram criados
    # path('admin-panel/cantina/', CanteenListView.as_view(), name='admin_cantina_list'),
    # path('admin-panel/cantina/new/', CanteenEditView.as_view(), name='admin_cantina_create'),
    # path('admin-panel/cantina/<int:debtor_id>/edit/', CanteenEditView.as_view(), name='admin_cantina_edit'),
    # path('admin-panel/cantina/<int:debtor_id>/', CanteenDetailView.as_view(), name='admin_cantina_detail'),
    # path('admin-panel/cantina/<int:debtor_id>/delete/', CanteenDeleteView.as_view(), name='admin_cantina_delete'),
    # path('admin-panel/cantina/<int:debtor_id>/toggle-paid/', CanteenTogglePaidView.as_view(), name='admin_cantina_toggle_paid'),
    # path('admin-panel/api/cantina/', CanteenApiView.as_view(), name='admin_cantina_api'),
    
    # Testemunhos URLs
    path('admin-panel/testimonies/', AdminTestimonyListView.as_view(), name='admin_testimonies_list'),
    path('admin-panel/testimonies/new/', TestimonyEditView.as_view(), name='admin_testimony_create'),
    path('admin-panel/testimonies/<int:testimony_id>/edit/', TestimonyEditView.as_view(), name='admin_testimony_edit'),
    path('admin-panel/testimonies/<int:testimony_id>/delete/', TestimonyDeleteView.as_view(), name='admin_testimony_delete'),
    path('admin-panel/testimonies/<int:testimony_id>/toggle/', TestimonyToggleView.as_view(), name='admin_testimony_toggle'),

    # Roteiro de Culto
    # Casa de Paz (admin)
    path('admin-panel/house-of-peace/', AdminHouseOfPeaceListView.as_view(), name='admin_house_of_peace_list'),
    path('admin-panel/house-of-peace/<int:house_id>/', AdminHouseOfPeaceDetailView.as_view(), name='admin_house_of_peace_detail'),
    path('admin-panel/house-of-peace/<int:house_id>/status/', AdminHouseOfPeaceStatusView.as_view(), name='admin_house_of_peace_status'),
    path('admin-panel/house-of-peace/<int:house_id>/delete/', AdminHouseOfPeaceDeleteView.as_view(), name='admin_house_of_peace_delete'),

    path('admin-panel/roteiro/', RoteiroView.as_view(), name='roteiro_view'),
    path('admin-panel/roteiro/anuncios/new/', AnuncioCreateView.as_view(), name='roteiro_anuncio_create'),
    path('admin-panel/roteiro/anuncios/<int:anuncio_id>/edit/', AnuncioEditView.as_view(), name='roteiro_anuncio_edit'),
    path('admin-panel/roteiro/anuncios/<int:anuncio_id>/delete/', AnuncioDeleteView.as_view(), name='roteiro_anuncio_delete'),
    path('admin-panel/roteiro/anuncios/reorder/', AnuncioReorderView.as_view(), name='roteiro_anuncio_reorder'),
    path('admin-panel/roteiro/print/', RoteiroPrintView.as_view(), name='roteiro_print'),

    # APIs
    path('admin-panel/api/delete/', ApiDeleteItemView.as_view(), name='admin_api_delete'),
    path('admin-panel/api/ministry/', MinistryCreateEditApiView.as_view(), name='admin_ministry_api'),
    path('admin-panel/api/neighborhood/', NeighborhoodCreateEditApiView.as_view(), name='admin_neighborhood_api'),
    path('admin-panel/api/member/<int:member_id>/', MemberDetailApiView.as_view(), name='admin_member_detail_api'),
    path('admin-panel/api/visitor/<int:visitor_id>/', VisitorDetailApiView.as_view(), name='admin_visitor_detail_api'),
    
    # Ministérios - Nova Gestão Escalável
    path('admin-panel/ministries/', MinistryListView.as_view(), name='ministry_list'),
    path('admin-panel/ministries/create/', MinistryCreateView.as_view(), name='ministry_create'),
    path('admin-panel/ministries/<int:pk>/edit/', MinistryUpdateView.as_view(), name='ministry_edit'),
    path('admin-panel/ministries/<int:pk>/delete/', MinistryDeleteView.as_view(), name='ministry_delete'),
    path('admin-panel/ministries/<int:pk>/members/', MinistryMembersView.as_view(), name='ministry_members'),
    path('admin-panel/ministries/<int:pk>/members/add/', MinistryAddMembersPageView.as_view(), name='ministry_add_members'),
    path('admin-panel/ministries/<int:ministry_id>/members/add/<int:member_id>/', MinistryAddMemberView.as_view(), name='ministry_add_member'),
    path('admin-panel/ministries/<int:ministry_id>/members/remove/<int:member_id>/', MinistryRemoveMemberView.as_view(), name='ministry_remove_member'),
    path('admin-panel/ministries/<int:ministry_id>/members/toggle-role/<int:member_id>/', MinistryToggleRoleView.as_view(), name='ministry_toggle_role'),
    path('admin-panel/ministries/<int:ministry_id>/members/toggle-status/<int:member_id>/', MinistryToggleStatusView.as_view(), name='ministry_toggle_status'),

    # Media Planning URLs
    path('media/', MediaDashboardView.as_view(), name='media_dashboard'),
    # Month Plans (wizard)
    path('media/planos/novo/', MediaMonthPlanCreateView.as_view(), name='media_plan_create'),
    path('media/planos/<int:year>/<int:month>/', MediaMonthPlanDetailView.as_view(), name='media_plan_detail'),
    path('media/planos/<int:year>/<int:month>/etapa/<int:step>/', MediaMonthPlanWizardView.as_view(), name='media_plan_step'),
    path('media/planos/<int:year>/<int:month>/evento/toggle/', MediaPlanToggleEventView.as_view(), name='media_plan_toggle_event'),
    path('media/planos/<int:year>/<int:month>/categoria/toggle/', MediaPlanToggleCategoryView.as_view(), name='media_plan_toggle_category'),
    path('media/planos/<int:year>/<int:month>/categoria/criar/', MediaContentCategoryCreateView.as_view(), name='media_plan_create_category'),
    path('media/planos/<int:year>/<int:month>/evento/criar/', MediaPlanCreateEventView.as_view(), name='media_plan_create_event'),
    path('media/planos/<int:year>/<int:month>/evento/<int:event_pk>/conteudos/', MediaPlanMacroEventView.as_view(), name='media_plan_macro_event'),
    path('media/planos/<int:year>/<int:month>/categoria/<int:category_pk>/conteudos/', MediaPlanMacroCategoryView.as_view(), name='media_plan_macro_category'),
    # Standalone content browse (outside plans)
    path('media/events/', MediaEventsView.as_view(), name='media_events'),
    path('media/events/sugestoes/', MediaEventSuggestionsView.as_view(), name='media_event_suggestions'),
    path('media/demands/', MediaDemandsView.as_view(), name='media_demands'),
    path('media/events/<int:pk>/edit/', MediaEventUpdateView.as_view(), name='media_event_update'),
    path('media/events/<int:pk>/remover-da-midia/', MediaEventRemoveFromMediaView.as_view(), name='media_event_remove_from_media'),
    path('media/events/<int:event_pk>/', MediaEventContentsView.as_view(), name='media_event_contents'),
    path('media/category/<str:content_type>/', MediaCategoryContentsView.as_view(), name='media_category_contents'),
    # Content CRUD
    path('media/contents/', MediaContentListView.as_view(), name='media_content_list'),
    path('media/contents/panel/', MediaDemandsPanelView.as_view(), name='media_demands_panel'),
    path('media/contents/criar/', MediaDemandQuickCreateView.as_view(), name='media_demand_quick_create'),
    path('media/contents/<int:pk>/editar-rapido/', MediaDemandQuickUpdateView.as_view(), name='media_demand_quick_update'),
    path('media/contents/evento/criar/', MediaEventQuickCreateView.as_view(), name='media_event_quick_create'),
    path('media/tipo-evento/criar-rapido/', MediaEventTypeQuickCreateView.as_view(), name='media_event_type_quick_create'),
    path('media/contents/create/', MediaContentCreateView.as_view(), name='media_content_create'),
    path('media/contents/<int:pk>/edit/', MediaContentUpdateView.as_view(), name='media_content_update'),
    path('media/contents/<int:pk>/delete/', MediaContentDeleteView.as_view(), name='media_content_delete'),
    path('media/contents/<int:pk>/tasks/create/', MediaTaskCreateView.as_view(), name='media_task_create'),
    path('media/tasks/<int:pk>/status/', MediaTaskUpdateStatusView.as_view(), name='media_task_update_status'),
    path('media/tasks/<int:pk>/descricao/', MediaTaskUpdateDescriptionView.as_view(), name='media_task_update_description'),
    path('media/contents/<int:pk>/comment/', MediaCommentCreateView.as_view(), name='media_comment_create'),
    path('media/contents/<int:pk>/attach/', MediaAttachmentCreateView.as_view(), name='media_attachment_create'),
    # Calendar
    path('media/calendar/', MediaCalendarView.as_view(), name='media_calendar'),
    path('media/calendar/events/', MediaCalendarEventsAPIView.as_view(), name='media_calendar_events'),
    path('media/calendar/contents/<int:pk>/reschedule/', MediaCalendarUpdateView.as_view(), name='media_calendar_update'),
    # Event types & templates
    path('media/tipos/', MediaEventTypeListView.as_view(), name='media_event_type_list'),
    path('media/tipos/novo/', MediaEventTypeCreateView.as_view(), name='media_event_type_create'),
    path('media/tipos/<int:pk>/editar/', MediaEventTypeUpdateView.as_view(), name='media_event_type_edit'),
    path('media/tipos/<int:pk>/excluir/', MediaEventTypeDeleteView.as_view(), name='media_event_type_delete'),
    path('media/templates/', MediaTemplateListView.as_view(), name='media_template_list'),
    path('media/templates/novo/', MediaTemplateCreateView.as_view(), name='media_template_create'),
    path('media/templates/tipo/<int:event_type_pk>/configurar/', MediaTemplateSetupView.as_view(), name='media_template_setup'),
    path('media/templates/<int:pk>/', MediaTemplateDetailView.as_view(), name='media_template_detail'),
    path('media/templates/<int:pk>/editar/', MediaTemplateUpdateView.as_view(), name='media_template_edit'),
    path('media/templates/<int:template_pk>/itens/novo/', MediaTemplateItemCreateView.as_view(), name='media_template_item_create'),
    path('media/templates/itens/<int:pk>/editar/', MediaTemplateItemUpdateView.as_view(), name='media_template_item_edit'),
    path('media/templates/itens/<int:pk>/excluir/', MediaTemplateItemDeleteView.as_view(), name='media_template_item_delete'),
    path('media/events/<int:event_pk>/tipo/', MediaEventSetTypeView.as_view(), name='media_event_set_type'),
    path('media/events/<int:event_pk>/aplicar-template/', MediaApplyTemplateView.as_view(), name='media_apply_template'),
    # Organization
    path('media/organizacao/', MediaOrganizationDashboardView.as_view(), name='media_organization'),
    path('media/organizacao/equipes/', MediaSubTeamListView.as_view(), name='media_subteam_list'),
    path('media/organizacao/equipes/nova/', MediaSubTeamCreateView.as_view(), name='media_subteam_create'),
    path('media/organizacao/equipes/<int:pk>/', MediaSubTeamDetailView.as_view(), name='media_subteam_detail'),
    path('media/organizacao/equipes/<int:pk>/editar/', MediaSubTeamUpdateView.as_view(), name='media_subteam_edit'),
    path('media/organizacao/equipes/<int:pk>/membros/', MediaSubTeamMemberAddView.as_view(), name='media_subteam_member_add'),
    path('media/organizacao/membros/<int:pk>/editar/', MediaSubTeamMemberUpdateView.as_view(), name='media_subteam_member_edit'),
    path('media/organizacao/membros/<int:pk>/remover/', MediaSubTeamMemberRemoveView.as_view(), name='media_subteam_member_remove'),
    path('media/organizacao/funcoes/', MediaRoleListView.as_view(), name='media_role_list'),
    path('media/organizacao/funcoes/nova/', MediaRoleCreateView.as_view(), name='media_role_create'),
    path('media/organizacao/lideranca/', MediaLeadershipListView.as_view(), name='media_leadership_list'),
    path('media/organizacao/lideranca/novo/', MediaLeadershipCreateView.as_view(), name='media_leadership_create'),
    path('media/organizacao/lideranca/<int:pk>/editar/', MediaLeadershipUpdateView.as_view(), name='media_leadership_edit'),
    path('media/organizacao/recursos/', MediaResourceListView.as_view(), name='media_resource_list'),
    path('media/organizacao/recursos/novo/', MediaResourceCreateView.as_view(), name='media_resource_create'),
    path('media/organizacao/recursos/<int:pk>/', MediaResourceDetailView.as_view(), name='media_resource_detail'),
    path('media/organizacao/recursos/<int:pk>/editar/', MediaResourceUpdateView.as_view(), name='media_resource_edit'),
    path('media/organizacao/recursos/<int:pk>/credenciais/', MediaResourceCredentialUpdateView.as_view(), name='media_resource_credential_update'),
    path('media/organizacao/recursos/<int:pk>/credenciais/revelar/', MediaResourceCredentialRevealView.as_view(), name='media_resource_credential_reveal'),
]
